// @generated by Hayate/scripts/gen-from-wit.mjs from Hayate/wit/hayate.wit — DO NOT EDIT.
//
// OP / ELEMENT_KIND / EVENT は Hayate の wit/hayate.wit が単一ソース。手書きで
// 編集せず、WIT を変えて Hayate 側で `node scripts/gen-from-wit.mjs` を再実行する。
import type { ElementKind } from '@tsubame/renderer-protocol';

/**
 * `apply_mutations` の op_kind コード。Hayate の wasm が公開する
 * `op_kind_*()` と 1:1 で一致する（同じ wit/hayate.wit から生成）。
 */
export const OP = {
  APPEND_CHILD: 0,
  INSERT_BEFORE: 1,
  REMOVE: 2,
  SET_ROOT: 3,
  SET_STYLE: 4,
  SET_TRANSFORM: 5,
  SET_SCROLL_OFFSET: 6,
  FOCUS: 7,
  BLUR: 8,
  CREATE: 9,
} as const;

/**
 * `ElementKind` → kind_code。Hayate の `element_kind_*()` と一致。
 * `OP.CREATE` の operand として ops ストリームに乗せる。
 */
export const ELEMENT_KIND: Record<ElementKind, number> = {
  view: 0,
  text: 1,
  image: 2,
  button: 3,
  'text-input': 4,
  'scroll-view': 5,
};

/**
 * `poll_events()` が返す各イベントの先頭判別子コード。Hayate の
 * `event_kind_*()` および encode_events の wire 値と一致する。
 */
export const EVENT = {
  CLICK: 0,
  FOCUS: 1,
  BLUR: 2,
  TEXT_INPUT: 3,
  COMPOSITION_START: 4,
  COMPOSITION_UPDATE: 5,
  COMPOSITION_END: 6,
  SCROLL: 7,
  RESIZE: 8,
  ACTIVE_END: 9,
  HOVER_ENTER: 10,
  HOVER_LEAVE: 11,
  KEY_DOWN: 12,
  ACTIVE_START: 13,
  POINTER_MOVE: 14,
} as const;
