packages:
  - 'Hayate'
  - 'Hayate/examples/web-demo/pkg'
  - 'Tsubame/packages/*'
  - 'Tsubame/examples/*'

allowBuilds:
  esbuild: true

minimumReleaseAgeExclude:
  - baseline-browser-mapping@2.10.33
  - tinyglobby@0.2.17

onlyBuiltDependencies:
  - esbuild
