packages:
  - 'Hayate'
  - 'Hayate/host'
  - 'Hayate/proto'
  - 'Hayate/wasm-pkgs/pkg'
  - 'Hayate/wasm-pkgs/pkg-tiny-skia'
  - 'Hayate/wasm-pkgs/pkg-null'
  - 'Tsubame'
  - 'Tsubame/proto'
  - 'Tsubame/packages/*'
  - 'Tsubame/examples/*'
  - 'Miharashi/dev-server'
  - 'Miharashi/host-web'
  - 'Miharashi/protocol-handshake'

allowBuilds:
  canvas: true
  esbuild: true

minimumReleaseAgeExclude:
  - baseline-browser-mapping@2.10.33
  - tinyglobby@0.2.17

onlyBuiltDependencies:
  - esbuild
