import { mkdir, readFile, writeFile } from 'node:fs/promises';
import { fileURLToPath } from 'node:url';

const repositoryRoot = fileURLToPath(new URL('../../../', import.meta.url));
const vocabulary = JSON.parse(await readFile(new URL('../spec/vocabulary.json', import.meta.url), 'utf8'));
const schema = JSON.parse(await readFile(new URL('../spec/wire.schema.json', import.meta.url), 'utf8'));

const generatedHeader = '// @generated by @torimi/wire-contract/scripts/generate.mjs. DO NOT EDIT.\n';
const snakeUpper = (value) => value.replace(/([a-z0-9])([A-Z])/g, '$1_$2').replace(/[^A-Za-z0-9]+/g, '_').toUpperCase();
const pascal = (value) => value.slice(0, 1).toUpperCase() + value.slice(1);
const routeConstant = (name) => {
  const upper = snakeUpper(name);
  return upper.includes('_ROUTE') ? upper : `${upper}_ROUTE`;
};
const routeCppName = (name) => name.includes('Route') ? name : `${name}Route`;
const entries = (value) => Object.entries(value).sort(([a], [b]) => a.localeCompare(b));
const stable = (value) => {
  if (Array.isArray(value)) return value.map(stable);
  if (value && typeof value === 'object') {
    return Object.fromEntries(Object.keys(value).sort().map((key) => [key, stable(value[key])]));
  }
  return value;
};
const literal = (value) => JSON.stringify(stable(value), null, 2);

function tsType(node) {
  if (node.$ref) return node.$ref.split('/').at(-1);
  if (node.type === 'array') return `readonly ${tsType(node.items)}[]`;
  if (node.type === 'integer' || node.type === 'number') return 'number';
  if (node.type === 'string') return 'string';
  if (node.type === 'boolean') return 'boolean';
  if (node.type === 'object') return 'Readonly<Record<string, unknown>>';
  return 'unknown';
}

const tsConstants = [
  ...entries(vocabulary.routes).map(([name, value]) => `export const ${routeConstant(name)} = ${JSON.stringify(value)} as const;`),
  ...entries(vocabulary.messages).map(([name, value]) => `export const ${snakeUpper(name)}_MESSAGE = ${JSON.stringify(value)} as const;`),
  ...entries(vocabulary.globals).map(([name, value]) => `export const ${snakeUpper(name)}_GLOBAL = ${JSON.stringify(value)} as const;`),
];

const tsVocabularies = entries(vocabulary.vocabularies).flatMap(([name, definition]) => {
  const typeName = pascal(name);
  const values = [...definition.values].sort();
  const lines = values.map((value) => `export const ${snakeUpper(name)}_${snakeUpper(value)} = ${JSON.stringify(value)} as const;`);
  lines.push(`export const KNOWN_${snakeUpper(name)}S = [${values.map((value) => `${snakeUpper(name)}_${snakeUpper(value)}`).join(', ')}] as const;`);
  lines.push(`export type ${typeName} = string;`);
  lines.push(`export function isKnown${typeName}(value: string): value is (typeof KNOWN_${snakeUpper(name)}S)[number] {`);
  lines.push(`  return (KNOWN_${snakeUpper(name)}S as readonly string[]).includes(value);`);
  lines.push('}');
  return lines;
});

const tsInterfaces = Object.entries(schema.$defs).sort(([a], [b]) => a.localeCompare(b)).map(([name, definition]) => {
  const required = new Set(definition.required ?? []);
  const fields = Object.entries(definition.properties ?? {}).sort(([a], [b]) => a.localeCompare(b)).map(([field, fieldSchema]) =>
    `  readonly ${field}${required.has(field) ? '' : '?'}: ${tsType(fieldSchema)};`
  );
  return `export interface ${name} {\n${fields.join('\n')}\n}`;
});

const tsSchemaLiteral = literal({ $defs: schema.$defs });
const ts = `${generatedHeader}
${tsConstants.join('\n')}

${tsVocabularies.join('\n')}

${tsInterfaces.join('\n\n')}

export interface WireIssue {
  readonly path: string;
  readonly expected: string;
  readonly actualType: string;
}

export type WireValidationResult<T> =
  | { readonly ok: true; readonly value: T }
  | { readonly ok: false; readonly issues: readonly WireIssue[] };

type JsonSchema = Readonly<Record<string, unknown>>;
const WIRE_SCHEMA = ${tsSchemaLiteral} as const;

function actualType(value: unknown): string {
  if (value === null) return 'null';
  if (Array.isArray(value)) return 'array';
  return typeof value;
}

function check(value: unknown, rawSchema: JsonSchema, path: string, issues: WireIssue[]): void {
  let candidate = rawSchema;
  if (typeof candidate.$ref === 'string') {
    const name = candidate.$ref.split('/').at(-1);
    candidate = (WIRE_SCHEMA.$defs as Record<string, JsonSchema>)[name ?? ''] ?? {};
  }
  const expected = typeof candidate.type === 'string' ? candidate.type : 'valid wire value';
  const fail = (): void => { issues.push({ path, expected, actualType: actualType(value) }); };
  if (candidate.type === 'object') {
    if (value === null || typeof value !== 'object' || Array.isArray(value)) return fail();
    const record = value as Record<string, unknown>;
    for (const field of (candidate.required as readonly string[] | undefined) ?? []) {
      if (!Object.prototype.hasOwnProperty.call(record, field)) {
        issues.push({ path: path + '.' + field, expected: 'required', actualType: 'missing' });
      }
    }
    for (const [field, fieldSchema] of Object.entries((candidate.properties as Record<string, JsonSchema> | undefined) ?? {})) {
      if (Object.prototype.hasOwnProperty.call(record, field)) check(record[field], fieldSchema, path + '.' + field, issues);
    }
    return;
  }
  if (candidate.type === 'array') {
    if (!Array.isArray(value)) return fail();
    value.forEach((item, index) => check(item, candidate.items as JsonSchema, path + '[' + index + ']', issues));
    return;
  }
  if (candidate.type === 'integer') {
    if (typeof value !== 'number' || !Number.isFinite(value) || !Number.isInteger(value) || (typeof candidate.minimum === 'number' && value < candidate.minimum)) fail();
    return;
  }
  if (candidate.type === 'number') {
    if (typeof value !== 'number' || !Number.isFinite(value)) fail();
    return;
  }
  if (candidate.type === 'string') {
    if (typeof value !== 'string' || (typeof candidate.minLength === 'number' && value.length < candidate.minLength)) fail();
    return;
  }
  if (candidate.type === 'boolean' && typeof value !== 'boolean') fail();
}

function validate<T>(name: keyof typeof WIRE_SCHEMA.$defs, value: unknown): WireValidationResult<T> {
  const issues: WireIssue[] = [];
  check(value, WIRE_SCHEMA.$defs[name], '$', issues);
  return issues.length === 0 ? { ok: true, value: value as T } : { ok: false, issues };
}

${Object.keys(schema.$defs).sort().map((name) => `export function validate${name}(value: unknown): WireValidationResult<${name}> {\n  return validate('${name}', value);\n}`).join('\n')}

export const devServerContract = {
  bundleRoute: BUNDLE_ROUTE,
  reloadRoute: RELOAD_ROUTE,
  reloadMessage: RELOAD_MESSAGE,
  logRoutePrefix: LOG_ROUTE_PREFIX,
} as const;

export const demoEndpointContract = { demoManifestRoute: DEMO_MANIFEST_ROUTE } as const;
`;

function rustType(node) {
  if (node.$ref) return node.$ref.split('/').at(-1);
  if (node.type === 'array') return `Vec<${rustType(node.items)}>`;
  if (node.type === 'integer') return 'u64';
  if (node.type === 'number') return 'f64';
  if (node.type === 'string') return 'String';
  if (node.type === 'boolean') return 'bool';
  return 'serde_json::Value';
}
const rustConstants = [
  ...entries(vocabulary.routes).map(([name, value]) => `pub const ${routeConstant(name)}: &str = ${JSON.stringify(value)};`),
  ...entries(vocabulary.messages).map(([name, value]) => `pub const ${snakeUpper(name)}_MESSAGE: &str = ${JSON.stringify(value)};`),
  ...entries(vocabulary.globals).map(([name, value]) => `pub const ${snakeUpper(name)}_GLOBAL: &str = ${JSON.stringify(value)};`),
];
const rustVocab = entries(vocabulary.vocabularies).flatMap(([name, definition]) => {
  const upper = snakeUpper(name);
  const values = [...definition.values].sort();
  const knownValues = values.map((value) => `${upper}_${snakeUpper(value)}`);
  const knownArray = knownValues.length <= 2
    ? `&[${knownValues.join(', ')}]`
    : `&[\n${knownValues.map((value) => `    ${value},`).join('\n')}\n]`;
  return [
    ...values.map((value) => `pub const ${upper}_${snakeUpper(value)}: &str = ${JSON.stringify(value)};`),
    `pub const KNOWN_${upper}S: &[&str] = ${knownArray};`,
    `pub fn is_known_${name.replace(/([A-Z])/g, '_$1').toLowerCase()}(value: &str) -> bool {\n    KNOWN_${upper}S.contains(&value)\n}`,
  ];
});
const rustStructs = Object.entries(schema.$defs).sort(([a], [b]) => a.localeCompare(b)).map(([name, definition]) => {
  const fields = Object.entries(definition.properties ?? {}).sort(([a], [b]) => a.localeCompare(b)).map(([field, fieldSchema]) => {
    const rustName = field.replace(/([A-Z])/g, '_$1').toLowerCase();
    const attributes = fieldSchema.type === 'string' && fieldSchema.minLength > 0
      ? '    #[serde(deserialize_with = "deserialize_non_empty_string")]\n'
      : '';
    return `${attributes}    pub ${rustName}: ${rustType(fieldSchema)},`;
  });
  return `#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]\n#[serde(rename_all = "camelCase")]\npub struct ${name} {\n${fields.join('\n')}\n}`;
});
const rust = `${generatedHeader.replace('//', '//!')}
use serde::{Deserialize, Deserializer, Serialize};

fn deserialize_non_empty_string<'de, D>(deserializer: D) -> Result<String, D::Error>
where
    D: Deserializer<'de>,
{
    let value = String::deserialize(deserializer)?;
    if value.is_empty() {
        return Err(serde::de::Error::custom("expected a non-empty string"));
    }
    Ok(value)
}

${rustConstants.join('\n')}

${rustVocab.join('\n')}

${rustStructs.join('\n\n')}
`;

const cppConstants = [
  ...entries(vocabulary.routes).map(([name, value]) => [routeCppName(name), value]),
  ...entries(vocabulary.messages).map(([name, value]) => [`${name}Message`, value]),
  ...entries(vocabulary.globals).map(([name, value]) => [`${name}Global`, value]),
].sort(([a], [b]) => a.localeCompare(b)).map(([name, value]) => `inline constexpr std::string_view k${pascal(name)} = ${JSON.stringify(value)};`);
const cpp = `// @generated by @torimi/wire-contract/scripts/generate.mjs. DO NOT EDIT.
#pragma once
#include <string_view>

namespace torimi::wire {
${cppConstants.join('\n')}
}  // namespace torimi::wire
`;

await Promise.all([
  mkdir(`${repositoryRoot}Hayate/crates/platform/mobile/android/src/generated`, { recursive: true }),
  mkdir(`${repositoryRoot}Hayate/crates/platform/mobile/android/cpp/generated`, { recursive: true }),
]);
await Promise.all([
  writeFile(new URL('../src/generated.ts', import.meta.url), ts),
  writeFile(`${repositoryRoot}Hayate/crates/platform/mobile/android/src/generated/torimi_wire.rs`, rust),
  writeFile(`${repositoryRoot}Hayate/crates/platform/mobile/android/cpp/generated/torimi_wire.hpp`, cpp),
]);
