// @generated by Hayate/scripts/gen-from-wit.mjs from wit/hayate.wit — DO NOT EDIT.
//
// op_kind / element_kind / event_kind / modifier-keys の判別子は wit/hayate.wit が
// 単一ソース。手書きで編集せず、WIT を変えて `node scripts/gen-from-wit.mjs` を
// 再実行すること。

use wasm_bindgen::prelude::*;

// ── op-kind: apply_mutations の op_kind 判別子（ADR-0039）──
pub(crate) const OP_APPEND_CHILD: u32 = 0;
pub(crate) const OP_INSERT_BEFORE: u32 = 1;
pub(crate) const OP_REMOVE: u32 = 2;
pub(crate) const OP_SET_ROOT: u32 = 3;
pub(crate) const OP_SET_STYLE: u32 = 4;
pub(crate) const OP_SET_TRANSFORM: u32 = 5;
pub(crate) const OP_SET_SCROLL_OFFSET: u32 = 6;
pub(crate) const OP_FOCUS: u32 = 7;
pub(crate) const OP_BLUR: u32 = 8;
pub(crate) const OP_CREATE: u32 = 9;

#[wasm_bindgen]
pub fn op_kind_append_child() -> u32 {
    OP_APPEND_CHILD
}
#[wasm_bindgen]
pub fn op_kind_insert_before() -> u32 {
    OP_INSERT_BEFORE
}
#[wasm_bindgen]
pub fn op_kind_remove() -> u32 {
    OP_REMOVE
}
#[wasm_bindgen]
pub fn op_kind_set_root() -> u32 {
    OP_SET_ROOT
}
#[wasm_bindgen]
pub fn op_kind_set_style() -> u32 {
    OP_SET_STYLE
}
#[wasm_bindgen]
pub fn op_kind_set_transform() -> u32 {
    OP_SET_TRANSFORM
}
#[wasm_bindgen]
pub fn op_kind_set_scroll_offset() -> u32 {
    OP_SET_SCROLL_OFFSET
}
#[wasm_bindgen]
pub fn op_kind_focus() -> u32 {
    OP_FOCUS
}
#[wasm_bindgen]
pub fn op_kind_blur() -> u32 {
    OP_BLUR
}
#[wasm_bindgen]
pub fn op_kind_create() -> u32 {
    OP_CREATE
}

// ── element-kind: kind_code（ElementKind の discriminant と一致）──
#[wasm_bindgen]
pub fn element_kind_view() -> u32 {
    0
}
#[wasm_bindgen]
pub fn element_kind_text() -> u32 {
    1
}
#[wasm_bindgen]
pub fn element_kind_image() -> u32 {
    2
}
#[wasm_bindgen]
pub fn element_kind_button() -> u32 {
    3
}
#[wasm_bindgen]
pub fn element_kind_text_input() -> u32 {
    4
}
#[wasm_bindgen]
pub fn element_kind_scroll_view() -> u32 {
    5
}

// ── event: poll_events() の wire 判別子（encode_events が参照）──
pub(crate) const EVENT_CLICK: f64 = 0.0;
pub(crate) const EVENT_FOCUS: f64 = 1.0;
pub(crate) const EVENT_BLUR: f64 = 2.0;
pub(crate) const EVENT_TEXT_INPUT: f64 = 3.0;
pub(crate) const EVENT_COMPOSITION_START: f64 = 4.0;
pub(crate) const EVENT_COMPOSITION_UPDATE: f64 = 5.0;
pub(crate) const EVENT_COMPOSITION_END: f64 = 6.0;
pub(crate) const EVENT_SCROLL: f64 = 7.0;
pub(crate) const EVENT_RESIZE: f64 = 8.0;
pub(crate) const EVENT_ACTIVE_END: f64 = 9.0;
pub(crate) const EVENT_HOVER_ENTER: f64 = 10.0;
pub(crate) const EVENT_HOVER_LEAVE: f64 = 11.0;
pub(crate) const EVENT_KEY_DOWN: f64 = 12.0;
pub(crate) const EVENT_ACTIVE_START: f64 = 13.0;
pub(crate) const EVENT_POINTER_MOVE: f64 = 14.0;

#[wasm_bindgen]
pub fn event_kind_click() -> f64 {
    EVENT_CLICK
}
#[wasm_bindgen]
pub fn event_kind_focus() -> f64 {
    EVENT_FOCUS
}
#[wasm_bindgen]
pub fn event_kind_blur() -> f64 {
    EVENT_BLUR
}
#[wasm_bindgen]
pub fn event_kind_text_input() -> f64 {
    EVENT_TEXT_INPUT
}
#[wasm_bindgen]
pub fn event_kind_composition_start() -> f64 {
    EVENT_COMPOSITION_START
}
#[wasm_bindgen]
pub fn event_kind_composition_update() -> f64 {
    EVENT_COMPOSITION_UPDATE
}
#[wasm_bindgen]
pub fn event_kind_composition_end() -> f64 {
    EVENT_COMPOSITION_END
}
#[wasm_bindgen]
pub fn event_kind_scroll() -> f64 {
    EVENT_SCROLL
}
#[wasm_bindgen]
pub fn event_kind_resize() -> f64 {
    EVENT_RESIZE
}
#[wasm_bindgen]
pub fn event_kind_active_end() -> f64 {
    EVENT_ACTIVE_END
}
#[wasm_bindgen]
pub fn event_kind_hover_enter() -> f64 {
    EVENT_HOVER_ENTER
}
#[wasm_bindgen]
pub fn event_kind_hover_leave() -> f64 {
    EVENT_HOVER_LEAVE
}
#[wasm_bindgen]
pub fn event_kind_key_down() -> f64 {
    EVENT_KEY_DOWN
}
#[wasm_bindgen]
pub fn event_kind_active_start() -> f64 {
    EVENT_ACTIVE_START
}
#[wasm_bindgen]
pub fn event_kind_pointer_move() -> f64 {
    EVENT_POINTER_MOVE
}

// ── modifier-keys: KeyboardEvent 修飾キーのビットマスク ──
#[wasm_bindgen]
pub fn modifier_shift() -> u32 {
    1
}
#[wasm_bindgen]
pub fn modifier_ctrl() -> u32 {
    2
}
#[wasm_bindgen]
pub fn modifier_alt() -> u32 {
    4
}
#[wasm_bindgen]
pub fn modifier_meta() -> u32 {
    8
}
