import { writeFileSync, mkdirSync } from 'fs';
import { join, dirname } from 'path';
import { fileURLToPath } from 'url';
import {
  loadProtocolSpec,
  tagToPatchKey,
  toCamelCase,
  toKebabCase,
} from '@hayate/protocol-spec/load';

const outDir = join(dirname(fileURLToPath(import.meta.url)), '../generated');
const jsonOutPath = join(outDir, 'catalog.json');
const tsOutPath = join(outDir, 'catalog.ts');

/** DOM-only side effects not represented in protocol spec wire format. */
const DOM_EXTRAS = {
  borderWidth: [
    {
      cssName: 'borderStyle',
      cssProperty: 'border-style',
      whenPositive: 'solid',
      whenZero: 'none',
    },
  ],
};

function wireKind(tag) {
  if (tag.name === 'FONT_FAMILY' || tag.name === 'DEFAULT_FONT_FAMILY') return 'fontFamily';
  if (tag.name === 'Z_INDEX') return 'zIndex';
  const param = (tag.params ?? [])[0];
  if (!param) return 'f32';
  switch (param.type) {
    case 'color':
      return 'color';
    case 'dimension':
      return 'dimension';
    case 'display':
      return 'display';
    case 'flex_direction':
      return 'flexDirection';
    case 'align_items':
      return 'alignItems';
    case 'justify_content':
      return 'justifyContent';
    case 'font_style':
      return 'fontStyle';
    case 'text_decoration':
      return 'textDecoration';
    case 'f32':
      return 'f32';
    default:
      return 'f32';
  }
}

function domFormat(tag, kind) {
  if (kind === 'dimension') return 'dimension';
  if (kind === 'color') return 'color';
  if (kind === 'fontFamily') return 'string';
  if (kind === 'zIndex') return 'integer';
  if (
    kind === 'display' ||
    kind === 'flexDirection' ||
    kind === 'alignItems' ||
    kind === 'justifyContent' ||
    kind === 'fontStyle' ||
    kind === 'textDecoration'
  ) {
    return 'enum';
  }
  if (kind === 'f32') {
    if (tag.name === 'OPACITY' || tag.name === 'FLEX_GROW' || tag.name === 'FONT_WEIGHT') return 'number';
    return 'px';
  }
  return 'number';
}

export function generateCatalog() {
  const proto = loadProtocolSpec();

  const unsetByPatchKey = new Map();
  for (const uk of proto.unset_kinds ?? []) {
    unsetByPatchKey.set(tagToPatchKey(uk.name), {
      name: toCamelCase(uk.name),
      value: uk.value,
    });
  }

  const catalog = (proto.style_tags ?? []).map((tag) => {
    const patchKey = tagToPatchKey(tag.name);
    const kind = wireKind(tag);
    const unset = unsetByPatchKey.get(patchKey);
    const entry = {
      patchKey,
      tag: tag.value,
      unsetKind: unset ? unset.value : null,
      wireKind: kind,
      domFormat: domFormat(tag, kind),
      cssName: patchKey,
      cssProperty: toKebabCase(patchKey),
      targets: ['packet', 'css'],
    };
    const extras = DOM_EXTRAS[patchKey];
    if (extras) entry.domExtras = extras;
    return entry;
  });

  mkdirSync(outDir, { recursive: true });
  writeFileSync(jsonOutPath, `${JSON.stringify(catalog, null, 2)}\n`, 'utf8');

  const tsLines = [
    '// AUTO-GENERATED by Tsubame/proto/generator — DO NOT EDIT',
    '// Source: @hayate/protocol-spec',
    '',
    "import type { HayateDimension } from '@tsubame/renderer-protocol';",
    '',
    "export type WireKind = 'color' | 'dimension' | 'display' | 'flexDirection' | 'alignItems' | 'justifyContent' | 'fontStyle' | 'textDecoration' | 'f32' | 'zIndex' | 'fontFamily';",
    "export type DomFormat = 'dimension' | 'px' | 'number' | 'integer' | 'color' | 'enum' | 'string';",
    '',
    'export interface DomExtra {',
    '  readonly cssName: string;',
    '  readonly cssProperty: string;',
    '  readonly whenPositive: string;',
    '  readonly whenZero: string;',
    '}',
    '',
    'export interface CatalogEntry {',
    '  readonly patchKey: string;',
    '  readonly tag: number;',
    '  readonly unsetKind: number | null;',
    '  readonly wireKind: WireKind;',
    '  readonly domFormat: DomFormat;',
    '  readonly cssName: string;',
    '  readonly cssProperty: string;',
    '  readonly targets: readonly ("packet" | "css")[];',
    '  readonly domExtras?: readonly DomExtra[];',
    '}',
    '',
    `export const HAYATE_CSS_CATALOG: readonly CatalogEntry[] = ${JSON.stringify(catalog, null, 2)};`,
    '',
    'export const CATALOG_BY_KEY: Readonly<Record<string, CatalogEntry>> = Object.fromEntries(',
    '  HAYATE_CSS_CATALOG.map((e) => [e.patchKey, e]),',
    ');',
    '',
    'export const CATALOG_BY_TAG: Readonly<Record<number, CatalogEntry>> = Object.fromEntries(',
    '  HAYATE_CSS_CATALOG.map((e) => [e.tag, e]),',
    ');',
    '',
    'export interface StyleEncodeEntry {',
    '  readonly key: string;',
    '  readonly tag: number;',
    '  readonly kind: WireKind;',
    '}',
    '',
    'export const STYLE_ENCODE_META: readonly StyleEncodeEntry[] = HAYATE_CSS_CATALOG.filter(',
    '  (e) => e.targets.includes("packet"),',
    ').map((e) => ({ key: e.patchKey, tag: e.tag, kind: e.wireKind }));',
    '',
    'export const INHERITED_UNSET: Partial<Record<string, number>> = Object.fromEntries(',
    '  HAYATE_CSS_CATALOG.filter((e): e is CatalogEntry & { unsetKind: number } => e.unsetKind !== null)',
    '    .map((e) => [e.patchKey, e.unsetKind]),',
    ');',
    '',
    'function formatDimension(value: HayateDimension): string {',
    '  return typeof value === "number" ? `${value}px` : value;',
    '}',
    '',
    'export function formatDomCSSValue(entry: CatalogEntry, value: unknown): string {',
    '  switch (entry.domFormat) {',
    '    case "dimension":',
    '      return formatDimension(value as HayateDimension);',
    '    case "px":',
    '      return `${value}px`;',
    '    case "integer":',
    '    case "number":',
    '    case "color":',
    '    case "enum":',
    '    case "string":',
    '      return String(value);',
    '    default: {',
    '      const _exhaustive: never = entry.domFormat;',
    '      throw new Error(`unsupported dom format ${_exhaustive}`);',
    '    }',
    '  }',
    '}',
    '',
    'export function applyDomExtras(',
    '  style: Record<string, string>,',
    '  entry: CatalogEntry,',
    '  value: unknown,',
    '): void {',
    '  if (!entry.domExtras) return;',
    '  for (const extra of entry.domExtras) {',
    '    const n = typeof value === "number" ? value : Number(value);',
    '    style[extra.cssName] = n > 0 ? extra.whenPositive : extra.whenZero;',
    '  }',
    '}',
    '',
  ];

  writeFileSync(tsOutPath, tsLines.join('\n'), 'utf8');
}
