// codegen-canvas-backend.lib.mjs — pure generator for
// Hayate/host/src/load-canvas-backend.generated.ts (#703).
//
// loadCanvasBackend's if/else branches and their `import()` bare specifiers
// used to be hand-written in Hayate/host/src/index.ts, one branch per
// backend. That's exactly the "add a backend, remember every call site"
// problem the wasm-build-manifest.json manifest (#700) exists to kill —
// this module derives the same branches from each target's `host` mapping
// instead. Kept free of fs access so the generated string can be
// unit-tested without writing a file.
//
// `import()` specifiers must stay static string literals in the generated
// output (so bundlers can statically analyze/code-split them) — this module
// achieves that by string-templating literal `import('...')` calls, never
// emitting a computed/dynamic specifier.

function hostTargets(manifest) {
  return manifest.targets.filter((t) => t.host !== null);
}

// Each backend maps to exactly one base target (no variantFlag) plus at most
// one flagged variant today (vello / layerPresent, ADR-0135) — not an
// arbitrary combinator, because that's the only shape that has ever existed
// here. A future second flag on the same backend is a deliberate enough
// change that it should fail loudly here rather than be silently guessed at.
function branchFor(backend, targets) {
  const base = targets.find((t) => !t.host.variantFlag);
  const variants = targets.filter((t) => t.host.variantFlag);
  if (!base) throw new Error(`codegen-canvas-backend: backend "${backend}" has no base (non-variant) target`);
  if (variants.length > 1) {
    throw new Error(`codegen-canvas-backend: backend "${backend}" has more than one variant target`);
  }

  const importExpr = variants.length
    ? `${variants[0].host.variantFlag} ? await import('${variants[0].npmName}') : await import('${base.npmName}')`
    : `await import('${base.npmName}')`;

  return `  if (backend === '${backend}') {
    const mod = ${importExpr};
    await mod.default();
    return (await mod.HayateElementRenderer.init(canvas)) as unknown as RawHayate;
  }`;
}

export function generateLoadCanvasBackend(manifest) {
  const targets = hostTargets(manifest);
  const backends = [...new Set(targets.map((t) => t.host.backend))];
  const branches = backends.map((backend) => branchFor(backend, targets.filter((t) => t.host.backend === backend)));

  return `// AUTO-GENERATED by Hayate/scripts/codegen-canvas-backend.mjs — DO NOT EDIT
// Source: Hayate/scripts/wasm-build-manifest.json (#700/#703)
import type { CanvasBackend } from './resolve-backend.js';
import type { RawHayate } from './raw-hayate.js';

/**
 * 選択した backend の WASM を動的 import し、surface（canvas）上で \`HayateElementRenderer\`
 * を初期化して {@link RawHayate} を得る。canvas のコンテキスト型は一度決まると変えられ
 * ないため、WebGPU の可否を判定してから WASM 初期化に進む。
 *
 * \`layerPresent\` は vello の per-layer 経路（ADR-0125/0127）の有効化。ADR-0137 により
 * Web は既定 ON — \`false\` を渡すと全面 raster 版（\`hayate-adapter-web\`）に戻せる、
 * 比較用の逃げ道として残す。native は本パスを経由しないため既定 OFF のまま変更なし。
 */
export async function loadCanvasBackend(
  backend: CanvasBackend,
  canvas: HTMLCanvasElement,
  layerPresent = true,
): Promise<RawHayate> {
${branches.join('\n')}
  throw new Error(\`loadCanvasBackend: no wasm-build-manifest.json target maps to backend "\${backend}"\`);
}
`;
}
