// codegen-canvas-backend.lib.mjs — pure generator for
// Hayate/host/src/load-canvas-backend.generated.ts (#703).
//
// loadCanvasBackend's if/else branches and their `import()` bare specifiers
// used to be hand-written in Hayate/host/src/index.ts, one branch per
// backend. That's exactly the "add a backend, remember every call site"
// problem the wasm-build-manifest.json manifest (#700) exists to kill —
// this module derives the same branches from each target's `host` mapping
// instead. Kept free of fs access so the generated string can be
// unit-tested without writing a file.
//
// `import()` specifiers must stay static string literals in the generated
// output (so bundlers can statically analyze/code-split them) — this module
// achieves that by string-templating literal `import('...')` calls, never
// emitting a computed/dynamic specifier.

function hostTargets(manifest) {
  return manifest.targets.filter((t) => t.host !== null);
}

// Each backend maps to exactly one target — not an arbitrary combinator,
// because that's the only shape that has ever existed here (ADR-0140/#718
// retired the one prior exception, vello's compile-time layerPresent
// package variant). A second target for the same backend is a deliberate
// enough change that it should fail loudly here rather than be silently
// guessed at.
function branchFor(backend, targets) {
  if (targets.length > 1) {
    throw new Error(`codegen-canvas-backend: backend "${backend}" has more than one target`);
  }
  const [target] = targets;

  // ADR-0138 (#710)/ADR-0140 (#718): a target opts into a runtime per-layer-present toggle by
  // naming the init() variable it wants (e.g. `cpuLayerPresent`, `layerPresent`).
  const initArgs = target.host.runtimeLayerPresentArg ? `canvas, ${target.host.runtimeLayerPresentArg}` : 'canvas';
  const bootstrap = target.host.bootstrap === 'canvaskit' ? '    await prepareCanvasKitSurface(canvas);\n' : '';

  return `  if (backend === '${backend}') {
${bootstrap}    const mod = await import('${target.npmName}');
    await mod.default();
    return (await mod.HayateElementRenderer.init(${initArgs})) as unknown as RawHayate;
  }`;
}

export function generateLoadCanvasBackend(manifest) {
  const targets = hostTargets(manifest);
  const needsCanvasKitBootstrap = targets.some((target) => target.host.bootstrap === 'canvaskit');
  const backends = [...new Set(targets.map((t) => t.host.backend))];
  const branches = backends.map((backend) => branchFor(backend, targets.filter((t) => t.host.backend === backend)));
  // `layerPresent` always exists as its own parameter (vello's own runtime toggle, see the
  // JSDoc below) — a target naming its runtime arg `layerPresent` would be a redundant
  // duplicate param.
  const runtimeArgs = [...new Set(targets.map((t) => t.host.runtimeLayerPresentArg).filter(Boolean))].filter(
    (name) => name !== 'layerPresent',
  );
  const needsCpuLayerPresent = runtimeArgs.length > 0;

  return `// AUTO-GENERATED by Hayate/scripts/codegen-canvas-backend.mjs — DO NOT EDIT
// Source: Hayate/scripts/wasm-build-manifest.json (#700/#703)
import type { CanvasBackend } from './resolve-backend.js';
import type { RawHayate } from './raw-hayate.js';
${needsCanvasKitBootstrap ? "import { prepareCanvasKitSurface } from './canvaskit-bridge.js';" : ''}

/**
 * 選択した backend の WASM を動的 import し、surface（canvas）上で \`HayateElementRenderer\`
 * を初期化して {@link RawHayate} を得る。canvas のコンテキスト型は一度決まると変えられ
 * ないため、WebGPU の可否を判定してから WASM 初期化に進む。
${needsCanvasKitBootstrap ? ' * CanvasKit は Host が先に surface を確立し、WASM 側は opaque な frame replay 境界だけを使う。\n' : ''}
 *
 * \`layerPresent\` は vello 専用のランタイムトグル（per-layer 経路、ADR-0125/0127・ADR-0140）。
 * \`HayateElementRenderer.init\` にランタイムフラグとして渡す。ADR-0137 により Web は既定
 * ON — \`false\` を渡すと全面 raster にフォールバックできる、比較用の逃げ道として残す。
 * native は本パスを経由しないため既定 OFF のまま変更なし。${
   needsCpuLayerPresent
     ? `
 *
 * \`cpuLayerPresent\` は tiny-skia/vello_cpu の per-layer 経路の比較用トグル（ADR-0138）。
 * vello の \`layerPresent\`（上記）とは別物の意味を持つが、同じ機構（\`HayateElementRenderer.init\`
 * へのランタイムフラグ）で渡す。既定 ON、\`false\` で全面 raster にフォールバックする。`
     : ''
 }
 */
export async function loadCanvasBackend(
  backend: CanvasBackend,
  canvas: HTMLCanvasElement,
  layerPresent = true,${runtimeArgs.map((name) => `\n  ${name} = true,`).join('')}
): Promise<RawHayate> {
${branches.join('\n')}
  throw new Error(\`loadCanvasBackend: no wasm-build-manifest.json target maps to backend "\${backend}"\`);
}
`;
}
