// AUTO-GENERATED by Hayate/scripts/codegen-canvas-backend.mjs — DO NOT EDIT
// Source: Hayate/scripts/wasm-build-manifest.json (#700/#703)
import type { CanvasBackend } from './resolve-backend.js';
import type { RawHayate } from './raw-hayate.js';

/**
 * 選択した backend の WASM を動的 import し、surface（canvas）上で `HayateElementRenderer`
 * を初期化して {@link RawHayate} を得る。canvas のコンテキスト型は一度決まると変えられ
 * ないため、WebGPU の可否を判定してから WASM 初期化に進む。
 *
 * `layerPresent` は vello の per-layer 経路（ADR-0125/0127）の有効化。ADR-0137 により
 * Web は既定 ON — `false` を渡すと全面 raster 版（`hayate-adapter-web`）に戻せる、
 * 比較用の逃げ道として残す。native は本パスを経由しないため既定 OFF のまま変更なし。
 *
 * `cpuLayerPresent` は tiny-skia/vello_cpu の per-layer 経路の比較用トグル（ADR-0138）。
 * vello の `layerPresent`（パッケージ選択、コンパイル時）とは別物 — こちらはランタイム
 * フラグとして `HayateElementRenderer.init` に渡す。既定 ON、`false` で全面 raster
 * にフォールバックする。
 */
export async function loadCanvasBackend(
  backend: CanvasBackend,
  canvas: HTMLCanvasElement,
  layerPresent = true,
  cpuLayerPresent = true,
): Promise<RawHayate> {
  if (backend === 'vello') {
    const mod = layerPresent ? await import('hayate-adapter-web-layer-present') : await import('hayate-adapter-web');
    await mod.default();
    return (await mod.HayateElementRenderer.init(canvas)) as unknown as RawHayate;
  }
  if (backend === 'tiny-skia') {
    const mod = await import('hayate-adapter-web-cpu');
    await mod.default();
    return (await mod.HayateElementRenderer.init(canvas, cpuLayerPresent)) as unknown as RawHayate;
  }
  if (backend === 'vello-cpu') {
    const mod = await import('hayate-adapter-web-vello-cpu');
    await mod.default();
    return (await mod.HayateElementRenderer.init(canvas, cpuLayerPresent)) as unknown as RawHayate;
  }
  throw new Error(`loadCanvasBackend: no wasm-build-manifest.json target maps to backend "${backend}"`);
}
