// AUTO-GENERATED by Hayate/scripts/codegen-canvas-backend.mjs — DO NOT EDIT
// Source: Hayate/scripts/wasm-build-manifest.json (#700/#703)
import type { CanvasBackend } from './resolve-backend.js';
import type { RawHayate } from './raw-hayate.js';

/**
 * 選択した backend の WASM を動的 import し、surface（canvas）上で `HayateElementRenderer`
 * を初期化して {@link RawHayate} を得る。canvas のコンテキスト型は一度決まると変えられ
 * ないため、WebGPU の可否を判定してから WASM 初期化に進む。
 *
 * `layerPresent` は ADR-0135 が定める本人調査用の明示的な例外のみに使う（既定 false）。
 */
export async function loadCanvasBackend(
  backend: CanvasBackend,
  canvas: HTMLCanvasElement,
  layerPresent = false,
): Promise<RawHayate> {
  if (backend === 'vello') {
    const mod = layerPresent ? await import('hayate-adapter-web-layer-present') : await import('hayate-adapter-web');
    await mod.default();
    return (await mod.HayateElementRenderer.init(canvas)) as unknown as RawHayate;
  }
  if (backend === 'tiny-skia') {
    const mod = await import('hayate-adapter-web-cpu');
    await mod.default();
    return (await mod.HayateElementRenderer.init(canvas)) as unknown as RawHayate;
  }
  if (backend === 'vello-cpu') {
    const mod = await import('hayate-adapter-web-vello-cpu');
    await mod.default();
    return (await mod.HayateElementRenderer.init(canvas)) as unknown as RawHayate;
  }
  throw new Error(`loadCanvasBackend: no wasm-build-manifest.json target maps to backend "${backend}"`);
}
