use std::fs;
use std::path::Path;

use serde::Deserialize;

mod value_type;
use value_type::ValueType;

const GENERATED_HEADER: &str = "// AUTO-GENERATED by Hayate/proto/generator — DO NOT EDIT\n// Source: proto/spec/*.json\n\n";

/// Generate protocol.rs, dispatch.rs, dom_style_mapper.rs, event_types.rs,
/// pseudo_state_tables.rs and element_kind_tables.rs into `out_dir`.
pub fn generate_all(spec_dir: &Path, out_dir: &Path) {
    fs::create_dir_all(out_dir).expect("cannot create output directory");

    let proto = load_spec(spec_dir);
    let code = generate(&proto);
    let codec = generate_codec(&proto);
    let mutation_sink = generate_mutation_sink(&proto);
    let dispatch = generate_dispatch(&proto);
    let event_encode_web = generate_encode_event_js(&proto);
    let dom_mapper = generate_dom_style_mapper(&proto);
    let event_types = generate_event_types(&proto);
    let pseudo_state_tables = generate_pseudo_state_tables(&proto);
    let element_kind_tables = generate_element_kind_tables(&proto);

    fs::write(out_dir.join("protocol.rs"), code).unwrap();
    fs::write(out_dir.join("codec.rs"), codec).unwrap();
    fs::write(out_dir.join("mutation_sink.rs"), mutation_sink).unwrap();
    fs::write(out_dir.join("dispatch.rs"), dispatch).unwrap();
    // Web 専用の js_sys イベントエンコーダ（ADR-0112）。中立な protocol.rs から
    // 分離し、Android の generated include には含めない。
    fs::write(out_dir.join("event_encode_web.rs"), event_encode_web).unwrap();
    fs::write(out_dir.join("dom_style_mapper.rs"), dom_mapper).unwrap();
    fs::write(out_dir.join("event_types.rs"), event_types).unwrap();
    fs::write(out_dir.join("pseudo_state_tables.rs"), pseudo_state_tables).unwrap();
    fs::write(out_dir.join("element_kind_tables.rs"), element_kind_tables).unwrap();
}

// ---------------------------------------------------------------------------
// Data model
// ---------------------------------------------------------------------------

#[derive(Default)]
struct Proto {
    types: Vec<TypeDef>,
    enums: Vec<EnumDef>,
    opcodes: Vec<Entry>,
    style_tags: Vec<Entry>,
    event_kinds: Vec<Entry>,
    element_kinds: Vec<SimpleEntry>,
    unset_kinds: Vec<SimpleEntry>,
    modifier_keys: Vec<SimpleEntry>,
    pseudo_states: Vec<PseudoStateEntry>,
}

#[derive(Default)]
struct TypeDef {
    name: String,
    #[allow(dead_code)]
    raw_slots: usize,
    fields: Vec<Param>,
}

#[derive(Default)]
struct EnumDef {
    name: String,
    #[allow(dead_code)]
    string_values: bool,
    values: Vec<EnumValue>,
}

#[derive(Default, Clone)]
struct EnumValue {
    name: String,
    value: String, // numeric string or quoted string
}

#[derive(Default)]
struct Entry {
    name: String,
    value: u32,
    variable_length: bool,
    /// Style Channel: `text-local` / `ambient` / `none` (style_tags only).
    inherit: Option<String>,
    params: Vec<Param>,
    #[allow(dead_code)]
    encode_from: Option<String>,
    wire_role: Option<String>,
    adapter_tier: Option<String>,
    document_runtime: bool,
    bubbles: bool,
    #[allow(dead_code)]
    interaction_kind: Option<String>,
    description: Option<String>,
    dom_css: Option<DomCss>,
}

#[derive(Default, Clone)]
struct DomCss {
    property: String,
    format: String,
    extras: Vec<DomExtra>,
}

#[derive(Default, Clone)]
struct DomExtra {
    property: String,
    when_positive: String,
    when_zero: String,
}

#[derive(Default, Clone)]
struct Param {
    name: String,
    typ: String,
    count: usize, // 0 means 1 (no count attribute)
}

#[derive(Default)]
struct SimpleEntry {
    name: String,
    value: u32,
    /// Text-Local Carrier: carries channel-1 styles as CSS (element_kinds only).
    carries_text_local: bool,
    /// UA default cursor for this kind when no explicit `cursor` is set
    /// (element_kinds only; ADR-0105). A `cursor` enum value name; `None` means
    /// the kind has no default (resolves to `Default`).
    default_cursor: Option<String>,
    /// UA default `user-select` for this kind when no explicit `user-select` is
    /// set (element_kinds only; ADR-0108). A `user_select` enum value name;
    /// `None` means the kind has no default (resolves to `None`/unselectable).
    default_user_select: Option<String>,
    /// Whether this kind accepts text entry and so surfaces the platform soft
    /// keyboard / IME when focused (element_kinds only; #392).
    accepts_text_input: bool,
}

#[derive(Default)]
struct PseudoStateEntry {
    name: String,
    value: u32,
    priority: u32,
    css_pseudo: String,
}

// ---------------------------------------------------------------------------
// JSON spec loader (proto/spec/*.json)
// ---------------------------------------------------------------------------

#[derive(Deserialize)]
struct ParamJson {
    name: String,
    #[serde(rename = "type")]
    typ: String,
    #[serde(default)]
    count: usize,
}

#[derive(Deserialize)]
struct EntryJson {
    name: String,
    value: u32,
    #[serde(default)]
    inherit: Option<String>,
    #[serde(default)]
    variable_length: bool,
    #[serde(default)]
    params: Vec<ParamJson>,
    #[serde(default, rename = "encodeFrom")]
    encode_from: Option<String>,
    #[serde(default, rename = "wireRole")]
    wire_role: Option<String>,
    #[serde(default, rename = "adapterTier")]
    adapter_tier: Option<String>,
    #[serde(default, rename = "documentRuntime")]
    document_runtime: bool,
    #[serde(default)]
    bubbles: bool,
    #[serde(default, rename = "interactionKind")]
    interaction_kind: Option<String>,
    #[serde(default)]
    description: Option<String>,
    #[serde(default, rename = "domCss")]
    dom_css: Option<DomCssJson>,
}

#[derive(Deserialize)]
struct DomCssJson {
    property: String,
    format: String,
    #[serde(default)]
    extras: Vec<DomExtraJson>,
}

#[derive(Deserialize)]
struct DomExtraJson {
    property: String,
    #[serde(rename = "whenPositive")]
    when_positive: String,
    #[serde(rename = "whenZero")]
    when_zero: String,
}

#[derive(Deserialize)]
struct TypeJson {
    name: String,
    raw_slots: usize,
    fields: Vec<ParamJson>,
}

#[derive(Deserialize)]
struct EnumValueJson {
    name: String,
    value: serde_json::Value,
}

#[derive(Deserialize)]
struct EnumJson {
    name: String,
    #[serde(default)]
    string_values: bool,
    values: Vec<EnumValueJson>,
}

#[derive(Deserialize)]
struct SimpleJson {
    name: String,
    value: u32,
    #[serde(default, rename = "carriesTextLocal")]
    carries_text_local: bool,
    #[serde(default, rename = "defaultCursor")]
    default_cursor: Option<String>,
    #[serde(default, rename = "defaultUserSelect")]
    default_user_select: Option<String>,
    #[serde(default, rename = "acceptsTextInput")]
    accepts_text_input: bool,
}

#[derive(Deserialize)]
struct PseudoStateJson {
    name: String,
    value: u32,
    priority: u32,
    #[serde(rename = "cssPseudo")]
    css_pseudo: String,
}

fn read_json<T: for<'de> Deserialize<'de>>(spec_dir: &Path, name: &str) -> T {
    let path = spec_dir.join(name);
    let text = fs::read_to_string(&path)
        .unwrap_or_else(|e| panic!("cannot read {}: {}", path.display(), e));
    serde_json::from_str(&text)
        .unwrap_or_else(|e| panic!("invalid JSON in {}: {}", path.display(), e))
}

fn enum_value_string(value: &serde_json::Value) -> String {
    match value {
        serde_json::Value::Number(n) => n.to_string(),
        serde_json::Value::String(s) => s.clone(),
        other => panic!("invalid enum value: {other}"),
    }
}

fn load_spec(spec_dir: &Path) -> Proto {
    let types: Vec<TypeJson> = read_json(spec_dir, "types.json");
    let enums: Vec<EnumJson> = read_json(spec_dir, "enums.json");
    let opcodes: Vec<EntryJson> = read_json(spec_dir, "opcodes.json");
    let style_tags: Vec<EntryJson> = read_json(spec_dir, "style_tags.json");
    let event_kinds: Vec<EntryJson> = read_json(spec_dir, "event_kinds.json");
    let element_kinds: Vec<SimpleJson> = read_json(spec_dir, "element_kinds.json");
    let unset_kinds: Vec<SimpleJson> = read_json(spec_dir, "unset_kinds.json");
    let modifier_keys: Vec<SimpleJson> = read_json(spec_dir, "modifier_keys.json");
    let pseudo_states: Vec<PseudoStateJson> = read_json(spec_dir, "pseudo_states.json");

    Proto {
        types: types
            .into_iter()
            .map(|t| TypeDef {
                name: t.name,
                raw_slots: t.raw_slots,
                fields: t
                    .fields
                    .into_iter()
                    .map(|f| Param {
                        name: f.name,
                        typ: f.typ,
                        count: f.count,
                    })
                    .collect(),
            })
            .collect(),
        enums: enums
            .into_iter()
            .map(|e| EnumDef {
                name: e.name,
                string_values: e.string_values,
                values: e
                    .values
                    .into_iter()
                    .map(|v| EnumValue {
                        name: v.name,
                        value: enum_value_string(&v.value),
                    })
                    .collect(),
            })
            .collect(),
        opcodes: entries_from_json(opcodes),
        style_tags: entries_from_json(style_tags),
        event_kinds: entries_from_json(event_kinds),
        element_kinds: simple_from_json(element_kinds),
        unset_kinds: simple_from_json(unset_kinds),
        modifier_keys: simple_from_json(modifier_keys),
        pseudo_states: pseudo_states
            .into_iter()
            .map(|e| PseudoStateEntry {
                name: e.name,
                value: e.value,
                priority: e.priority,
                css_pseudo: e.css_pseudo,
            })
            .collect(),
    }
}

fn entries_from_json(entries: Vec<EntryJson>) -> Vec<Entry> {
    entries
        .into_iter()
        .map(|e| Entry {
            name: e.name,
            value: e.value,
            variable_length: e.variable_length,
            inherit: e.inherit,
            params: e
                .params
                .into_iter()
                .map(|p| Param {
                    name: p.name,
                    typ: p.typ,
                    count: p.count,
                })
                .collect(),
            encode_from: e.encode_from,
            wire_role: e.wire_role,
            adapter_tier: e.adapter_tier,
            document_runtime: e.document_runtime,
            bubbles: e.bubbles,
            interaction_kind: e.interaction_kind,
            description: e.description,
            dom_css: e.dom_css.map(|d| DomCss {
                property: d.property,
                format: d.format,
                extras: d
                    .extras
                    .into_iter()
                    .map(|x| DomExtra {
                        property: x.property,
                        when_positive: x.when_positive,
                        when_zero: x.when_zero,
                    })
                    .collect(),
            }),
        })
        .collect()
}

fn simple_from_json(entries: Vec<SimpleJson>) -> Vec<SimpleEntry> {
    entries
        .into_iter()
        .map(|e| SimpleEntry {
            name: e.name,
            value: e.value,
            carries_text_local: e.carries_text_local,
            default_cursor: e.default_cursor,
            default_user_select: e.default_user_select,
            accepts_text_input: e.accepts_text_input,
        })
        .collect()
}

// ---------------------------------------------------------------------------
// Code generator
// ---------------------------------------------------------------------------

fn param_slots(p: &Param) -> usize {
    let count = if p.count == 0 { 1 } else { p.count };
    count
}

fn param_rust_type(typ: &str, count: usize) -> String {
    let base = match typ {
        "element_id" => "u64",
        "u32" => "u32",
        "f32" => "f32",
        "f64" => "f64",
        "bool" => "bool",
        "usize" => "usize",
        "string" => "String",
        other => other, // enums etc. – not used in Op/StyleTag
    };
    if count > 1 {
        format!("[{}; {}]", base, count)
    } else {
        base.to_string()
    }
}

fn generate(proto: &Proto) -> String {
    let mut out = String::new();

    out.push_str(GENERATED_HEADER);

    // OP_* constants
    out.push_str("// Opcode constants\n");
    for op in &proto.opcodes {
        out.push_str(&format!(
            "pub const OP_{}: u32 = {};\n",
            op.name, op.value
        ));
    }
    out.push('\n');

    // OP_SLOTS
    out.push_str("// Payload slot counts per opcode (op discriminant excluded)\n");
    out.push_str("pub const OP_SLOTS: &[usize] = &[\n");
    for op in &proto.opcodes {
        let slots: usize = op.params.iter().map(param_slots).sum();
        out.push_str(&format!(
            "    {}, // {}\n",
            slots, op.name
        ));
    }
    out.push_str("];\n\n");

    // TAG_* constants
    out.push_str("// Style tag constants\n");
    for tag in &proto.style_tags {
        out.push_str(&format!(
            "pub const TAG_{}: u32 = {};\n",
            tag.name, tag.value
        ));
    }
    out.push('\n');

    // EVENT_KIND_* constants (f64)
    out.push_str("// Event kind constants\n");
    for ev in &proto.event_kinds {
        out.push_str(&format!(
            "pub const EVENT_KIND_{}: f64 = {}.0;\n",
            ev.name.to_uppercase(),
            ev.value
        ));
    }
    out.push('\n');

    out.push_str("// Event wire metadata (from event_kinds.json)\n");
    for ev in &proto.event_kinds {
        let wire_role = ev
            .wire_role
            .as_deref()
            .unwrap_or_else(|| panic!("event_kinds.{}: missing wireRole", ev.name));
        let adapter_tier = ev
            .adapter_tier
            .as_deref()
            .unwrap_or_else(|| panic!("event_kinds.{}: missing adapterTier", ev.name));
        out.push_str(&format!(
            "pub const EVENT_WIRE_ROLE_{}: &str = \"{}\";\n",
            ev.name.to_uppercase(),
            wire_role
        ));
        out.push_str(&format!(
            "pub const EVENT_ADAPTER_TIER_{}: &str = \"{}\";\n",
            ev.name.to_uppercase(),
            adapter_tier
        ));
    }
    out.push('\n');

    // ELEMENT_KIND_* constants
    out.push_str("// Element kind constants\n");
    for ek in &proto.element_kinds {
        out.push_str(&format!(
            "pub const ELEMENT_KIND_{}: u32 = {};\n",
            ek.name.to_uppercase(),
            ek.value
        ));
    }
    out.push('\n');

    // UNSET_KIND_* constants
    out.push_str("// Unset kind constants\n");
    for uk in &proto.unset_kinds {
        out.push_str(&format!(
            "pub const UNSET_KIND_{}: u32 = {};\n",
            uk.name.to_uppercase(),
            uk.value
        ));
    }
    out.push('\n');

    // MODIFIER_* constants
    out.push_str("// Modifier key constants\n");
    for mk in &proto.modifier_keys {
        out.push_str(&format!(
            "pub const MODIFIER_{}: u32 = {};\n",
            mk.name.to_uppercase(),
            mk.value
        ));
    }
    out.push('\n');

    // Op enum
    out.push_str("// Op enum\n");
    out.push_str("#[derive(Debug, Clone)]\n");
    out.push_str("pub enum Op {\n");
    for op in &proto.opcodes {
        // Convert SNAKE_UPPER to PascalCase
        let variant = to_pascal(&op.name);
        if op.params.is_empty() {
            out.push_str(&format!("    {},\n", variant));
        } else {
            out.push_str(&format!("    {} {{\n", variant));
            for p in &op.params {
                let count = if p.count == 0 { 1 } else { p.count };
                let rust_ty = param_rust_type(&p.typ, count);
                out.push_str(&format!("        {}: {},\n", p.name, rust_ty));
            }
            out.push_str("    },\n");
        }
    }
    out.push_str("}\n\n");

    // parse_next_op
    out.push_str("pub fn parse_next_op(ops: &[f64], i: usize) -> Result<(Op, usize), &'static str> {\n");
    out.push_str("    if i >= ops.len() { return Err(\"unexpected end of ops\"); }\n");
    out.push_str("    let disc = ops[i] as u32;\n");
    out.push_str("    let i = i + 1;\n");
    out.push_str("    match disc {\n");
    for op in &proto.opcodes {
        let variant = to_pascal(&op.name);
        let total_slots: usize = op.params.iter().map(param_slots).sum();
        out.push_str(&format!("        {} => {{\n", op.value));
        out.push_str(&format!(
            "            if i + {} > ops.len() {{ return Err(\"op {} truncated\"); }}\n",
            total_slots, op.name
        ));
        let mut slot = 0usize;
        for p in &op.params {
            let count = if p.count == 0 { 1 } else { p.count };
            if count > 1 {
                out.push_str(&format!("            let mut {} = [0f64; {}];\n", p.name, count));
                for ci in 0..count {
                    out.push_str(&format!(
                        "            {}[{}] = ops[i + {}];\n",
                        p.name,
                        ci,
                        slot + ci
                    ));
                }
            } else {
                let cast = match p.typ.as_str() {
                    "element_id" => "ops[i + IDX] as u64",
                    "u32" => "ops[i + IDX] as u32",
                    "f32" => "ops[i + IDX] as f32",
                    "f64" => "ops[i + IDX]",
                    "bool" => "ops[i + IDX] != 0.0",
                    "usize" => "ops[i + IDX] as usize",
                    _ => "ops[i + IDX] as u64",
                };
                let cast = cast.replace("IDX", &slot.to_string());
                out.push_str(&format!("            let {} = {};\n", p.name, cast));
            }
            slot += count;
        }
        if op.params.is_empty() {
            out.push_str(&format!("            Ok((Op::{}, i))\n", variant));
        } else {
            let field_list: Vec<String> = op.params.iter().map(|p| p.name.clone()).collect();
            out.push_str(&format!(
                "            Ok((Op::{} {{ {} }}, i + {}))\n",
                variant,
                field_list.join(", "),
                total_slots
            ));
        }
        out.push_str("        }\n");
    }
    out.push_str("        _ => Err(\"unknown opcode\"),\n");
    out.push_str("    }\n");
    out.push_str("}\n\n");

    // StyleTag enum
    out.push_str("// StyleTag enum\n");
    out.push_str("#[derive(Debug, Clone)]\n");
    out.push_str("pub enum StyleTag {\n");
    for tag in &proto.style_tags {
        let variant = to_pascal(&tag.name);
        if ValueType::classify(tag).is_dimension_list() {
            out.push_str(&format!("    {} {{\n", variant));
            out.push_str("        tracks: Vec<(f32, f32)>,\n");
            out.push_str("    },\n");
        } else if ValueType::classify(tag).is_shadow_list() {
            out.push_str(&format!("    {} {{\n", variant));
            out.push_str("        shadows: Vec<[f32; 9]>,\n");
            out.push_str("    },\n");
        } else if tag.params.is_empty() {
            out.push_str(&format!("    {},\n", variant));
        } else {
            // flatten compound types to raw f32
            let fields = flatten_tag_params(&tag.params, proto);
            if fields.is_empty() {
                out.push_str(&format!("    {},\n", variant));
            } else {
                out.push_str(&format!("    {} {{\n", variant));
                for (fname, ftype) in &fields {
                    out.push_str(&format!("        {}: {},\n", fname, ftype));
                }
                out.push_str("    },\n");
            }
        }
    }
    out.push_str("}\n\n");

    // parse_next_style_tag
    out.push_str("pub fn parse_next_style_tag(packed: &[f32], i: usize) -> Result<(StyleTag, usize), &'static str> {\n");
    out.push_str("    if i >= packed.len() { return Err(\"unexpected end of style data\"); }\n");
    out.push_str("    let tag = packed[i] as u32;\n");
    out.push_str("    let i = i + 1;\n");
    out.push_str("    match tag {\n");
    for tag in &proto.style_tags {
        let variant = to_pascal(&tag.name);
        let fields = flatten_tag_params(&tag.params, proto);
        let slot_count = fields.len();
        out.push_str(&format!("        {} => {{\n", tag.value));
        if tag.variable_length && ValueType::classify(tag).is_dimension_list() {
            out.push_str("            if i >= packed.len() { return Err(\"style tag track list truncated\"); }\n");
            out.push_str("            let track_count = packed[i] as usize;\n");
            out.push_str("            let mut tracks = Vec::with_capacity(track_count);\n");
            out.push_str("            let mut j = i + 1;\n");
            out.push_str("            for _ in 0..track_count {\n");
            out.push_str("                if j + 2 > packed.len() { return Err(\"style tag track list data truncated\"); }\n");
            out.push_str("                tracks.push((packed[j], packed[j + 1]));\n");
            out.push_str("                j += 2;\n");
            out.push_str("            }\n");
            out.push_str(&format!(
                "            Ok((StyleTag::{} {{ tracks }}, j))\n",
                variant
            ));
        } else if tag.variable_length && ValueType::classify(tag).is_shadow_list() {
            out.push_str("            if i >= packed.len() { return Err(\"style tag shadow list truncated\"); }\n");
            out.push_str("            let shadow_count = packed[i] as usize;\n");
            out.push_str("            let mut shadows = Vec::with_capacity(shadow_count);\n");
            out.push_str("            let mut j = i + 1;\n");
            out.push_str("            for _ in 0..shadow_count {\n");
            out.push_str("                if j + 9 > packed.len() { return Err(\"style tag shadow list data truncated\"); }\n");
            out.push_str("                shadows.push([\n");
            out.push_str("                    packed[j], packed[j + 1], packed[j + 2], packed[j + 3],\n");
            out.push_str("                    packed[j + 4], packed[j + 5], packed[j + 6], packed[j + 7], packed[j + 8],\n");
            out.push_str("                ]);\n");
            out.push_str("                j += 9;\n");
            out.push_str("            }\n");
            out.push_str(&format!(
                "            Ok((StyleTag::{} {{ shadows }}, j))\n",
                variant
            ));
        } else if tag.variable_length {
            // string: [byte_len, byte0, byte1, …] — one UTF-8 byte per f32 slot (wire format)
            out.push_str("            if i >= packed.len() { return Err(\"style tag string truncated\"); }\n");
            out.push_str("            let byte_len = packed[i] as usize;\n");
            out.push_str("            if i + 1 + byte_len > packed.len() { return Err(\"style tag string data truncated\"); }\n");
            out.push_str("            let bytes: Vec<u8> = (0..byte_len).map(|j| packed[i + 1 + j] as u8).collect();\n");
            out.push_str("            let family = String::from_utf8(bytes).map_err(|_| \"invalid utf8 in font family\")?;\n");
            out.push_str(&format!(
                "            Ok((StyleTag::{} {{ family }}, i + 1 + byte_len))\n",
                variant
            ));
        } else if fields.is_empty() {
            out.push_str(&format!("            Ok((StyleTag::{}, i))\n", variant));
        } else {
            out.push_str(&format!(
                "            if i + {} > packed.len() {{ return Err(\"style tag {} truncated\"); }}\n",
                slot_count, tag.name
            ));
            let mut si = 0usize;
            for (fname, _ftype) in &fields {
                out.push_str(&format!(
                    "            let {} = packed[i + {}];\n",
                    fname, si
                ));
                si += 1;
            }
            let field_list: Vec<String> = fields.iter().map(|(n, _)| n.clone()).collect();
            out.push_str(&format!(
                "            Ok((StyleTag::{} {{ {} }}, i + {}))\n",
                variant,
                field_list.join(", "),
                slot_count
            ));
        }
        out.push_str("        }\n");
    }
    out.push_str("        _ => Err(\"unknown style tag\"),\n");
    out.push_str("    }\n");
    out.push_str("}\n\n");

    out.push_str(&generate_style_codec(proto));
    out.push_str(&generate_encode_event_wire(proto));

    out
}

fn generate_style_codec(proto: &Proto) -> String {
    let mut out = String::new();

    out.push_str("// ── Style packet codec (generated) ─────────────────────────────────────\n\n");
    out.push_str("use hayate_core::{\n");
    out.push_str("    AlignContentValue, AlignSelfValue, AlignValue, BorderStyleValue, Color, CursorValue, Dimension, DimensionUnit,\n");
    out.push_str("    DisplayValue,\n");
    out.push_str("    FlexDirectionValue, FlexWrapValue, FontStyleValue, JustifyValue, OverflowValue, PositionValue, Shadow, StyleProp, TextDecorationValue, TextOverflowValue,\n");
    out.push_str("    TransitionTimingValue,\n");
    out.push_str("};\n\n");

    out.push_str("fn codec_dim(value: f32, unit_raw: f32) -> Dimension {\n");
    out.push_str("    let unit = match unit_raw as u32 {\n");
    out.push_str("        0 => DimensionUnit::Px,\n");
    out.push_str("        1 => DimensionUnit::Percent,\n");
    out.push_str("        2 => DimensionUnit::Auto,\n");
    out.push_str("        3 => DimensionUnit::Fr,\n");
    out.push_str("        _ => DimensionUnit::Px,\n");
    out.push_str("    };\n");
    out.push_str("    Dimension { value, unit }\n");
    out.push_str("}\n\n");

    out.push_str("fn codec_color(r: f32, g: f32, b: f32, a: f32) -> Color {\n");
    out.push_str("    Color::new(r as f64, g as f64, b as f64, a as f64)\n");
    out.push_str("}\n\n");

    out.push_str("fn codec_shadow(s: [f32; 9]) -> Shadow {\n");
    out.push_str("    Shadow {\n");
    out.push_str("        offset_x: s[0],\n");
    out.push_str("        offset_y: s[1],\n");
    out.push_str("        blur: s[2],\n");
    out.push_str("        spread: s[3],\n");
    out.push_str("        color: codec_color(s[4], s[5], s[6], s[7]),\n");
    out.push_str("        inset: s[8] != 0.0,\n");
    out.push_str("    }\n");
    out.push_str("}\n\n");

    for en in &proto.enums {
        let rust_enum = match en.name.as_str() {
            "display" => "DisplayValue",
            "flex_direction" => "FlexDirectionValue",
            "flex_wrap" => "FlexWrapValue",
            "align_items" => "AlignValue",
            "align_self" => "AlignSelfValue",
            "align_content" => "AlignContentValue",
            "justify_content" => "JustifyValue",
            "font_style" => "FontStyleValue",
            "text_decoration" => "TextDecorationValue",
            "border_style" => "BorderStyleValue",
            "cursor" => "CursorValue",
            "overflow" => "OverflowValue",
            "text_overflow" => "TextOverflowValue",
            "position" => "PositionValue",
            "transition_timing" => "TransitionTimingValue",
            _ => continue,
        };
        let fn_name = format!("codec_{}", en.name);
        out.push_str(&format!("fn {fn_name}(raw: f32) -> {rust_enum} {{\n"));
        out.push_str("    match raw as u32 {\n");
        for v in &en.values {
            let variant = to_pascal(&v.name);
            out.push_str(&format!(
                "        {} => {rust_enum}::{variant},\n",
                v.value
            ));
        }
        let default_variant = to_pascal(&en.values[0].name);
        out.push_str(&format!("        _ => {rust_enum}::{default_variant},\n"));
        out.push_str("    }\n");
        out.push_str("}\n\n");
    }

    out.push_str("fn style_tag_to_prop(tag: StyleTag) -> Result<StyleProp, String> {\n");
    out.push_str("    Ok(match tag {\n");
    for tag in &proto.style_tags {
        let variant = to_pascal(&tag.name);
        let prop_variant = to_pascal(&tag.name);
        out.push_str(&format!("        StyleTag::{variant}"));
        if ValueType::classify(tag).is_dimension_list() {
            out.push_str(" { tracks } => ");
        } else if ValueType::classify(tag).is_shadow_list() {
            out.push_str(" { shadows } => ");
        } else {
            let fields = flatten_tag_params(&tag.params, proto);
            if fields.is_empty() {
                out.push_str(" => ");
            } else {
                let field_names: Vec<String> = fields.iter().map(|(n, _)| n.clone()).collect();
                out.push_str(&format!(" {{ {} }} => ", field_names.join(", ")));
            }
        }
        let vt = ValueType::classify(tag);
        let expr = vt.decode_to_prop_expr(&tag.params, proto);
        out.push_str(&format!("StyleProp::{prop_variant}({expr}),\n"));
    }
    out.push_str("    })\n");
    out.push_str("}\n\n");

    out.push_str(
        "pub fn decode_style_packet(packed: &[f32]) -> Result<Vec<StyleProp>, String> {\n",
    );
    out.push_str("    let mut out = Vec::new();\n");
    out.push_str("    let mut i = 0usize;\n");
    out.push_str("    while i < packed.len() {\n");
    out.push_str("        let (tag, next) = parse_next_style_tag(packed, i)\n");
    out.push_str("            .map_err(|e| e.to_string())?;\n");
    out.push_str("        i = next;\n");
    out.push_str("        out.push(style_tag_to_prop(tag)?);\n");
    out.push_str("    }\n");
    out.push_str("    Ok(out)\n");
    out.push_str("}\n\n");

    out
}

fn generate_codec(proto: &Proto) -> String {
    let mut out = String::new();
    out.push_str(GENERATED_HEADER);
    out.push_str("// ── Wire codec encode (generated) ────────────────────────────────────────\n\n");

    out.push_str("fn encode_dim_unit(unit: DimensionUnit) -> f32 {\n");
    out.push_str("    match unit {\n");
    out.push_str("        DimensionUnit::Px => 0.0,\n");
    out.push_str("        DimensionUnit::Percent => 1.0,\n");
    out.push_str("        DimensionUnit::Auto => 2.0,\n");
    out.push_str("        DimensionUnit::Fr => 3.0,\n");
    out.push_str("    }\n");
    out.push_str("}\n\n");

    for en in &proto.enums {
        let rust_enum = match en.name.as_str() {
            "display" => "DisplayValue",
            "flex_direction" => "FlexDirectionValue",
            "flex_wrap" => "FlexWrapValue",
            "align_items" => "AlignValue",
            "align_self" => "AlignSelfValue",
            "align_content" => "AlignContentValue",
            "justify_content" => "JustifyValue",
            "font_style" => "FontStyleValue",
            "text_decoration" => "TextDecorationValue",
            "border_style" => "BorderStyleValue",
            "cursor" => "CursorValue",
            "overflow" => "OverflowValue",
            "text_overflow" => "TextOverflowValue",
            "position" => "PositionValue",
            "transition_timing" => "TransitionTimingValue",
            _ => continue,
        };
        let fn_name = format!("encode_{}", en.name);
        out.push_str(&format!("fn {fn_name}(value: {rust_enum}) -> f32 {{\n"));
        out.push_str("    match value {\n");
        for v in &en.values {
            let variant = to_pascal(&v.name);
            out.push_str(&format!(
                "        {rust_enum}::{variant} => {}.0,\n",
                v.value
            ));
        }
        out.push_str("    }\n");
        out.push_str("}\n\n");
    }

    out.push_str("pub fn encode_op(buf: &mut Vec<f64>, op: &Op) {\n");
    out.push_str("    match op {\n");
    for op in &proto.opcodes {
        let variant = to_pascal(&op.name);
        if op.params.is_empty() {
            out.push_str(&format!("        Op::{variant} => buf.push(OP_{} as f64),\n", op.name));
            continue;
        }
        let fields: Vec<String> = op.params.iter().map(|p| p.name.clone()).collect();
        out.push_str(&format!(
            "        Op::{variant} {{ {} }} => {{\n",
            fields.join(", ")
        ));
        out.push_str(&format!("            buf.push(OP_{} as f64);\n", op.name));
        for p in &op.params {
            let count = if p.count == 0 { 1 } else { p.count };
            if count > 1 {
                out.push_str(&format!("            for slot in {name}.iter() {{\n", name = p.name));
                out.push_str("                buf.push(*slot);\n");
                out.push_str("            }\n");
            } else {
                let push = match p.typ.as_str() {
                    "element_id" | "u32" | "usize" => format!("buf.push(*{name} as f64);", name = p.name),
                    "f32" => format!("buf.push(*{name} as f64);", name = p.name),
                    "f64" => format!("buf.push(*{name});", name = p.name),
                    "bool" => format!("buf.push(if *{name} {{ 1.0 }} else {{ 0.0 }});", name = p.name),
                    other => panic!("unsupported op param type for encode: {other}"),
                };
                out.push_str(&format!("            {push}\n"));
            }
        }
        out.push_str("        }\n");
    }
    out.push_str("    }\n");
    out.push_str("}\n\n");

    out.push_str("pub fn encode_style_packet(buf: &mut Vec<f32>, props: &[StyleProp]) {\n");
    out.push_str("    for prop in props {\n");
    out.push_str("        match prop {\n");
    for tag in &proto.style_tags {
        let prop_variant = to_pascal(&tag.name);
        let vt = ValueType::classify(tag);
        let binding = vt.encode_binding();
        out.push_str(&format!("            StyleProp::{prop_variant}{binding} => {{\n"));
        out.push_str(&format!("                buf.push(TAG_{} as f32);\n", tag.name));
        out.push_str(&vt.encode_body());
        out.push_str("            }\n");
    }
    out.push_str("        }\n");
    out.push_str("    }\n");
    out.push_str("}\n");

    out
}

fn generate_dom_style_mapper(proto: &Proto) -> String {
    let mut out = String::new();

    out.push_str(GENERATED_HEADER);
    out.push_str("// ── Hayate CSS → browser CSS mapper (generated) ─────────────────────────\n\n");
    out.push_str("use web_sys::CssStyleDeclaration;\n\n");

    out.push_str("fn dom_css_dim(d: Dimension) -> String {\n");
    out.push_str("    match d.unit {\n");
    out.push_str("        DimensionUnit::Px => format!(\"{}px\", d.value),\n");
    out.push_str("        DimensionUnit::Percent => format!(\"{}%\", d.value),\n");
    out.push_str("        DimensionUnit::Auto => \"auto\".into(),\n");
    out.push_str("        DimensionUnit::Fr => format!(\"{}fr\", d.value),\n");
    out.push_str("    }\n");
    out.push_str("}\n\n");

    out.push_str("fn dom_css_hex(c: Color) -> String {\n");
    out.push_str("    let arr = c.to_array_f32();\n");
    out.push_str("    format!(\n");
    out.push_str("        \"#{:02x}{:02x}{:02x}\",\n");
    out.push_str("        (arr[0] * 255.0).round() as u8,\n");
    out.push_str("        (arr[1] * 255.0).round() as u8,\n");
    out.push_str("        (arr[2] * 255.0).round() as u8,\n");
    out.push_str("    )\n");
    out.push_str("}\n\n");

    out.push_str("fn dom_css_rgba(c: Color) -> String {\n");
    out.push_str("    let arr = c.to_array_f32();\n");
    out.push_str("    format!(\n");
    out.push_str("        \"rgba({}, {}, {}, {})\",\n");
    out.push_str("        (arr[0] * 255.0).round() as u8,\n");
    out.push_str("        (arr[1] * 255.0).round() as u8,\n");
    out.push_str("        (arr[2] * 255.0).round() as u8,\n");
    out.push_str("        arr[3],\n");
    out.push_str("    )\n");
    out.push_str("}\n\n");

    out.push_str("fn dom_css_shadow(s: &Shadow) -> String {\n");
    out.push_str("    let inset = if s.inset { \"inset \" } else { \"\" };\n");
    out.push_str("    format!(\n");
    out.push_str("        \"{}{}px {}px {}px {}px {}\",\n");
    out.push_str("        inset, s.offset_x, s.offset_y, s.blur, s.spread, dom_css_rgba(s.color),\n");
    out.push_str("    )\n");
    out.push_str("}\n\n");

    out.push_str(
        "pub fn style_prop_css_entries(prop: &StyleProp, out: &mut Vec<(String, String)>) {\n",
    );
    out.push_str("    match *prop {\n");

    for tag in &proto.style_tags {
        let variant = to_pascal(&tag.name);
        let vt = ValueType::classify(tag);
        let (binding, value_var) = vt.match_binding();
        let dom_css = tag
            .dom_css
            .as_ref()
            .unwrap_or_else(|| panic!("style tag {} missing domCss", tag.name));

        out.push_str(&format!("        StyleProp::{variant}{binding} => {{\n"));
        let body = vt.css_collect_lines(dom_css, value_var);
        for line in body.lines() {
            out.push_str(&format!("            {line}\n"));
        }
        out.push_str("        }\n");
    }

    out.push_str("    }\n");
    out.push_str("}\n\n");

    out.push_str(
        "pub fn apply_style_prop_to_dom(style: &CssStyleDeclaration, prop: &StyleProp) -> Result<(), JsValue> {\n",
    );
    out.push_str("    let mut entries = Vec::new();\n");
    out.push_str("    style_prop_css_entries(prop, &mut entries);\n");
    out.push_str("    for (property, value) in entries {\n");
    out.push_str("        style.set_property(&property, &value)?;\n");
    out.push_str("    }\n");
    out.push_str("    Ok(())\n");
    out.push_str("}\n\n");

    // ── Style Channel predicates (CONTEXT.md / ADR-0065 / ADR-0002) ──────────
    out.push_str(
        "// ── Style Channel predicates (generated) ───────────────────────────────\n\n",
    );
    let text_local: Vec<String> = proto
        .style_tags
        .iter()
        .filter(|t| t.inherit.as_deref() == Some("text-local"))
        .map(|t| format!("StyleProp::{}(..)", to_pascal(&t.name)))
        .collect();
    out.push_str("/// Whether `prop` is a channel-1 text-local style (Style Channel).\n");
    out.push_str("pub fn is_text_local(prop: &StyleProp) -> bool {\n");
    if text_local.is_empty() {
        out.push_str("    let _ = prop;\n    false\n");
    } else {
        out.push_str("    matches!(\n        prop,\n        ");
        out.push_str(&text_local.join("\n            | "));
        out.push_str("\n    )\n");
    }
    out.push_str("}\n\n");

    let carriers: Vec<String> = proto
        .element_kinds
        .iter()
        .filter(|k| k.carries_text_local)
        .map(|k| format!("hayate_core::ElementKind::{}", to_pascal(&k.name)))
        .collect();
    out.push_str(
        "/// Whether `kind` carries channel-1 text-local styles as CSS (Text-Local Carrier).\n",
    );
    out.push_str("pub fn carries_text_local(kind: hayate_core::ElementKind) -> bool {\n");
    if carriers.is_empty() {
        out.push_str("    let _ = kind;\n    false\n");
    } else {
        out.push_str("    matches!(\n        kind,\n        ");
        out.push_str(&carriers.join("\n            | "));
        out.push_str("\n    )\n");
    }
    out.push_str("}\n");

    out
}

/// Per-op `MutationSink` method signature: `(method_name, params_after_self)`.
/// Single source of truth shared by the trait emission and the dispatch bodies.
/// `FOCUS` / `BLUR` map to the hand-authored `apply_focus` / `apply_blur`
/// host-callback exceptions (ADR-0078); everything else is a mechanical data op.
fn sink_method_sig(op_name: &str) -> (&'static str, &'static str) {
    match op_name {
        "APPEND_CHILD" => ("append_child", ", parent: ElementId, child: ElementId"),
        "INSERT_BEFORE" => (
            "insert_before",
            ", parent: ElementId, child: ElementId, before: ElementId",
        ),
        "REMOVE" => ("remove", ", id: ElementId"),
        "SET_ROOT" => ("set_root", ", id: ElementId"),
        "SET_STYLE" => ("set_style", ", id: ElementId, props: Vec<StyleProp>"),
        "SET_TRANSFORM" => ("set_transform", ", id: ElementId, matrix: Option<[f64; 6]>"),
        "SET_SCROLL_OFFSET" => ("set_scroll_offset", ", id: ElementId, x: f32, y: f32"),
        "FOCUS" => ("apply_focus", ", id: ElementId"),
        "BLUR" => ("apply_blur", ", id: ElementId"),
        "CREATE" => ("create", ", id: ElementId, kind: ElementKind"),
        "SET_TEXT" => ("set_text", ", id: ElementId, text: &str"),
        "UNSET_STYLE" => ("unset_style", ", id: ElementId, kind: StylePropKind"),
        "SET_TEXT_CONTENT" => ("set_text_content", ", id: ElementId, text: &str"),
        "SET_DISABLED" => ("set_disabled", ", id: ElementId, disabled: bool"),
        "SET_SRC" => ("set_src", ", id: ElementId, url: &str"),
        "SET_PSEUDO_STYLE" => (
            "set_pseudo_style",
            ", id: ElementId, state: PseudoState, props: Vec<StyleProp>",
        ),
        "SET_STYLE_VARIANT" => (
            "set_style_variant",
            ", id: ElementId, condition: ViewportCondition, prop: StyleProp",
        ),
        "SET_USER_SELECT" => ("set_user_select", ", id: ElementId, value: UserSelectValue"),
        "SET_MULTILINE" => ("set_multiline", ", id: ElementId, multiline: bool"),
        "SET_ARIA_LABEL" => ("set_aria_label", ", id: ElementId, label: &str"),
        "SET_ROLE" => ("set_role", ", id: ElementId, role: &str"),
        "SET_FONT_FAMILY" => ("set_font_family", ", id: ElementId, family: &str"),
        other => panic!("sink_method_sig: unmapped opcode {other} (add a MutationSink mapping)"),
    }
}

/// Emit the mode-agnostic `MutationSink` trait — one method per wire op — from
/// `opcodes.json`. The decode (`dispatch.rs`) calls these with fully-decoded
/// semantic arguments; adapters supply only the irreducible difference between
/// an immediate tree-apply sink and a deferred command-enqueue sink (ADR-0052 /
/// ADR-0112 single neutral decode, now parameterised over the apply target).
fn generate_mutation_sink(proto: &Proto) -> String {
    let mut out = String::new();
    out.push_str(GENERATED_HEADER);
    out.push_str(
        "use hayate_core::{ElementId, ElementKind, PseudoState, StyleProp, StylePropKind, UserSelectValue, ViewportCondition};\n\n",
    );
    out.push_str("/// Mode-agnostic batched-mutation sink generated from `proto/spec/opcodes.json`.\n");
    out.push_str("/// One method per wire op, receiving fully-decoded semantic arguments from the\n");
    out.push_str("/// generated decode (`dispatch.rs`). `apply_focus` / `apply_blur` are host\n");
    out.push_str("/// callbacks, not data ops, and stay hand-authored exceptions (ADR-0078).\n");
    out.push_str("pub trait MutationSink {\n");
    for op in &proto.opcodes {
        let (method, params) = sink_method_sig(&op.name);
        out.push_str(&format!("    fn {method}(&mut self{params});\n"));
    }
    out.push_str("}\n");
    out
}

fn generate_dispatch(proto: &Proto) -> String {
    let mut out = String::new();
    out.push_str(GENERATED_HEADER);
    out.push_str(
        "use hayate_core::{ElementId, ElementKind, PseudoState, StylePropKind, UserSelectValue, ViewportCondition};\n\n",
    );
    out.push_str("use super::protocol::{Op, decode_style_packet, parse_next_op};\n");
    out.push_str("use super::mutation_sink::MutationSink;\n\n");

    out.push_str("pub fn unset_kind_from_u32(v: u32) -> Result<StylePropKind, String> {\n");
    out.push_str("    match v {\n");
    for uk in &proto.unset_kinds {
        out.push_str(&format!(
            "        {} => Ok(StylePropKind::{}),\n",
            uk.value,
            to_pascal(&uk.name)
        ));
    }
    out.push_str(
        "        _ => Err(format!(\"unknown unset style kind {v}\")),\n",
    );
    out.push_str("    }\n");
    out.push_str("}\n\n");

    out.push_str(
        "/// `OP_SET_STYLE_VARIANT` encodes an unset viewport-condition axis as -1.0 (ADR-0081).\n",
    );
    out.push_str("fn viewport_axis(raw: f32) -> Option<f32> {\n");
    out.push_str("    if raw < 0.0 { None } else { Some(raw) }\n");
    out.push_str("}\n\n");

    out.push_str("/// Decode a batched-mutation wire stream and drive a [`MutationSink`].\n");
    out.push_str("pub fn apply_mutations_to_sink<S: MutationSink + ?Sized>(\n");
    out.push_str("    sink: &mut S,\n");
    out.push_str("    ops: &[f64],\n");
    out.push_str("    styles: &[f32],\n");
    out.push_str("    texts: &[String],\n");
    out.push_str(") -> Result<(), String> {\n");
    out.push_str("    let mut i = 0usize;\n");
    out.push_str("    while i < ops.len() {\n");
    out.push_str("        let (op, next) = parse_next_op(ops, i).map_err(|e| e.to_string())?;\n");
    out.push_str("        i = next;\n");
    out.push_str("        apply_parsed_op(sink, op, styles, texts)?;\n");
    out.push_str("    }\n");
    out.push_str("    Ok(())\n");
    out.push_str("}\n\n");

    out.push_str("fn apply_parsed_op<S: MutationSink + ?Sized>(\n");
    out.push_str("    sink: &mut S,\n");
    out.push_str("    op: Op,\n");
    out.push_str("    styles: &[f32],\n");
    out.push_str("    texts: &[String],\n");
    out.push_str(") -> Result<(), String> {\n");
    out.push_str("    match op {\n");

    for op in &proto.opcodes {
        let variant = to_pascal(&op.name);
        if op.params.is_empty() {
            continue;
        }
        let fields: Vec<String> = op.params.iter().map(|p| p.name.clone()).collect();
        out.push_str(&format!(
            "        Op::{variant} {{ {} }} => {{\n",
            fields.join(", ")
        ));
        out.push_str(&dispatch_op_body(&op.name, &op.params));
        out.push_str("        }\n");
    }

    out.push_str("    }\n");
    out.push_str("}\n");
    out
}

/// The decode body for one opcode: wire fields → decoded semantic args → one
/// `sink.<method>(...)` call. The op-record fields are already bound by the
/// match arm; style packets / text-table / enum coercion are resolved here so
/// the sink only sees semantic Rust types.
fn dispatch_op_body(op_name: &str, _params: &[Param]) -> String {
    match op_name {
        "APPEND_CHILD" => {
            "            sink.append_child(\n                ElementId::from_u64(parent_id),\n                ElementId::from_u64(child_id),\n            );\n            Ok(())\n".to_string()
        }
        "INSERT_BEFORE" => {
            "            sink.insert_before(\n                ElementId::from_u64(parent_id),\n                ElementId::from_u64(child_id),\n                ElementId::from_u64(before_id),\n            );\n            Ok(())\n".to_string()
        }
        "REMOVE" => {
            "            sink.remove(ElementId::from_u64(id));\n            Ok(())\n".to_string()
        }
        "SET_ROOT" => {
            "            sink.set_root(ElementId::from_u64(id));\n            Ok(())\n".to_string()
        }
        "SET_STYLE" => {
            r#"            let slice = styles
                .get(style_offset..style_offset + style_len)
                .ok_or_else(|| "styles slice out of bounds in OP_SET_STYLE".to_string())?;
            let props = decode_style_packet(slice)?;
            sink.set_style(ElementId::from_u64(id), props);
            Ok(())
"#.to_string()
        }
        "SET_TRANSFORM" => {
            r#"            let matrix = if has_matrix {
                Some(matrix)
            } else {
                None
            };
            sink.set_transform(ElementId::from_u64(id), matrix);
            Ok(())
"#.to_string()
        }
        "SET_SCROLL_OFFSET" => {
            r#"            sink.set_scroll_offset(ElementId::from_u64(id), x as f32, y as f32);
            Ok(())
"#.to_string()
        }
        "FOCUS" => {
            "            sink.apply_focus(ElementId::from_u64(id));\n            Ok(())\n".to_string()
        }
        "BLUR" => {
            "            sink.apply_blur(ElementId::from_u64(id));\n            Ok(())\n".to_string()
        }
        "CREATE" => {
            r#"            let k = ElementKind::from_u32(kind)
                .ok_or_else(|| format!("unknown element kind {kind}"))?;
            sink.create(ElementId::from_u64(id), k);
            Ok(())
"#.to_string()
        }
        "SET_TEXT" => {
            r#"            let text = texts
                .get(text_index)
                .ok_or_else(|| "text index out of bounds in OP_SET_TEXT".to_string())?;
            sink.set_text(ElementId::from_u64(id), text);
            Ok(())
"#.to_string()
        }
        "SET_TEXT_CONTENT" => {
            r#"            let text = texts
                .get(text_index)
                .ok_or_else(|| "text index out of bounds in OP_SET_TEXT_CONTENT".to_string())?;
            sink.set_text_content(ElementId::from_u64(id), text);
            Ok(())
"#.to_string()
        }
        "SET_DISABLED" => {
            r#"            sink.set_disabled(ElementId::from_u64(id), disabled);
            Ok(())
"#.to_string()
        }
        "SET_USER_SELECT" => {
            // ADR-0108 `user-select` vocabulary (text=0, none=1, contains=2). The
            // u32 wire value is decoded to the semantic enum here; the per-mode
            // bridge (e.g. the Canvas Selection Region boolean) lives in the sink.
            r#"            let value = match value {
                1 => UserSelectValue::None,
                2 => UserSelectValue::Contains,
                _ => UserSelectValue::Text,
            };
            sink.set_user_select(ElementId::from_u64(id), value);
            Ok(())
"#.to_string()
        }
        "SET_MULTILINE" => {
            r#"            sink.set_multiline(ElementId::from_u64(id), multiline);
            Ok(())
"#.to_string()
        }
        "SET_SRC" => {
            r#"            let url = texts
                .get(text_index)
                .ok_or_else(|| "text index out of bounds in OP_SET_SRC".to_string())?;
            sink.set_src(ElementId::from_u64(id), url);
            Ok(())
"#.to_string()
        }
        "UNSET_STYLE" => {
            r#"            let kind = unset_kind_from_u32(kind)?;
            sink.unset_style(ElementId::from_u64(id), kind);
            Ok(())
"#.to_string()
        }
        "SET_PSEUDO_STYLE" => {
            r#"            let pseudo = PseudoState::from_u32(state)
                .ok_or_else(|| format!("unknown pseudo-state {state}"))?;
            let slice = styles
                .get(style_offset..style_offset + style_len)
                .ok_or_else(|| "styles slice out of bounds in OP_SET_PSEUDO_STYLE".to_string())?;
            let props = decode_style_packet(slice)?;
            sink.set_pseudo_style(ElementId::from_u64(id), pseudo, props);
            Ok(())
"#.to_string()
        }
        "SET_STYLE_VARIANT" => {
            r#"            let slice = styles
                .get(style_offset..style_offset + style_len)
                .ok_or_else(|| "styles slice out of bounds in OP_SET_STYLE_VARIANT".to_string())?;
            let mut props = decode_style_packet(slice)?;
            if props.len() != 1 {
                return Err("OP_SET_STYLE_VARIANT requires exactly one style property".to_string());
            }
            let prop = props.remove(0);
            let condition = ViewportCondition {
                min_width: viewport_axis(min_width),
                max_width: viewport_axis(max_width),
                min_height: viewport_axis(min_height),
                max_height: viewport_axis(max_height),
            };
            sink.set_style_variant(ElementId::from_u64(id), condition, prop);
            Ok(())
"#.to_string()
        }
        "SET_ARIA_LABEL" => {
            r#"            let label = texts
                .get(text_index)
                .ok_or_else(|| "text index out of bounds in OP_SET_ARIA_LABEL".to_string())?;
            sink.set_aria_label(ElementId::from_u64(id), label);
            Ok(())
"#.to_string()
        }
        "SET_ROLE" => {
            r#"            let role = texts
                .get(text_index)
                .ok_or_else(|| "text index out of bounds in OP_SET_ROLE".to_string())?;
            sink.set_role(ElementId::from_u64(id), role);
            Ok(())
"#.to_string()
        }
        "SET_FONT_FAMILY" => {
            r#"            let family = texts
                .get(text_index)
                .ok_or_else(|| "text index out of bounds in OP_SET_FONT_FAMILY".to_string())?;
            sink.set_font_family(ElementId::from_u64(id), family);
            Ok(())
"#.to_string()
        }
        other => format!(
            "            Err(\"unknown op {other}\".to_string())\n",
        ),
    }
}

/// Flatten style tag params: expand compound types (color, dimension) into raw f32 fields.
fn flatten_tag_params(params: &[Param], proto: &Proto) -> Vec<(String, String)> {
    let mut result = Vec::new();
    for p in params {
        if p.typ == "i32" {
            // i32 values (e.g. z-index) occupy one f32 wire slot
            result.push((p.name.clone(), "f32".to_string()));
            continue;
        }
        // Check if this param type matches a known compound type
        if let Some(td) = proto.types.iter().find(|t| t.name == p.typ) {
            // Expand fields
            for f in &td.fields {
                let fname = format!("{}_{}", p.name, f.name);
                result.push((fname, "f32".to_string()));
            }
        } else if p.typ == "string" {
            result.push((p.name.clone(), "String".to_string()));
        } else {
            // f32, display enums, etc. — all stored as f32
            result.push((p.name.clone(), "f32".to_string()));
        }
    }
    result
}

fn event_match_pattern(ev: &Entry, qualified: bool) -> String {
    let variant = to_pascal(&ev.name);
    let prefix = if qualified { "hayate_core::Event::" } else { "Event::" };
    if ev.params.is_empty() {
        format!("{}{}", prefix, variant)
    } else {
        let fields: Vec<String> = ev.params.iter().map(|p| p.name.clone()).collect();
        format!("{}{} {{ {} }}", prefix, variant, fields.join(", "))
    }
}

fn event_match_wildcard(ev: &Entry) -> String {
    let variant = to_pascal(&ev.name);
    if ev.params.is_empty() {
        format!("Event::{}", variant)
    } else {
        format!("Event::{} {{ .. }}", variant)
    }
}

fn encode_event_wire_param_push(param: &Param, field: &str) -> String {
    match param.typ.as_str() {
        "element_id" => format!(
            "            out.push(EventWireValue::Number({}.to_u64() as f64));\n",
            field
        ),
        "string" => format!(
            "            out.push(EventWireValue::Text({}.clone()));\n",
            field
        ),
        "f32" | "f64" | "u32" | "usize" | "bool" => {
            format!("            out.push(EventWireValue::Number(*{} as f64));\n", field)
        }
        "pointer_kind" => format!(
            "            out.push(EventWireValue::Number({}.to_u32() as f64));\n",
            field
        ),
        other => panic!("unsupported event param type: {other}"),
    }
}

fn generate_encode_event_wire(proto: &Proto) -> String {
    let mut out = String::new();

    out.push_str("#[derive(Debug, Clone, PartialEq)]\n");
    out.push_str("pub enum EventWireValue {\n");
    out.push_str("    Number(f64),\n");
    out.push_str("    Text(String),\n");
    out.push_str("}\n\n");

    out.push_str("pub fn encode_event_wire(ev: &hayate_core::Event) -> Vec<EventWireValue> {\n");
    out.push_str("    match ev {\n");

    for ev in &proto.event_kinds {
        out.push_str(&format!("        {} => {{\n", event_match_pattern(ev, true)));
        out.push_str("            let mut out = Vec::new();\n");
        out.push_str(&format!(
            "            out.push(EventWireValue::Number({}.0));\n",
            ev.value
        ));
        for p in &ev.params {
            out.push_str(&encode_event_wire_param_push(p, &p.name));
        }
        out.push_str("            out\n");
        out.push_str("        }\n");
    }

    out.push_str("    }\n");
    out.push_str("}\n\n");

    out
}

/// 生成: `js_sys::Array` ベースのイベントエンコーダ（Web 専用 / ADR-0112）。中立な
/// `encode_event_wire` を JS 配列行へ持ち上げる。wasm-bindgen / js_sys に依存するため
/// 専用ファイル `event_encode_web.rs` へ書き出し、Android からは include しない。
fn generate_encode_event_js(_proto: &Proto) -> String {
    let mut out = String::new();
    out.push_str(GENERATED_HEADER);
    out.push_str("// ── Event encode (js_sys, Web 専用) ─────────────────────────────────────\n\n");

    out.push_str("pub fn encode_event(ev: &hayate_core::Event) -> js_sys::Array {\n");
    out.push_str("    use wasm_bindgen::JsValue;\n");
    out.push_str("    let sub = js_sys::Array::new();\n");
    out.push_str("    for atom in encode_event_wire(ev) {\n");
    out.push_str("        match atom {\n");
    out.push_str("            EventWireValue::Number(n) => { sub.push(&JsValue::from_f64(n)); }\n");
    out.push_str("            EventWireValue::Text(s) => { sub.push(&JsValue::from_str(&s)); }\n");
    out.push_str("        }\n");
    out.push_str("    }\n");
    out.push_str("    sub\n");
    out.push_str("}\n\n");

    out.push_str("pub fn encode_events(events: &[hayate_core::Event]) -> js_sys::Array {\n");
    out.push_str("    let result = js_sys::Array::new();\n");
    out.push_str("    for ev in events {\n");
    out.push_str("        result.push(&encode_event(ev));\n");
    out.push_str("    }\n");
    out.push_str("    result\n");
    out.push_str("}\n\n");

    out.push_str(
        "pub fn encode_deliveries(deliveries: &[hayate_core::EventDelivery]) -> js_sys::Array {\n",
    );
    out.push_str("    let result = js_sys::Array::new();\n");
    out.push_str("    for delivery in deliveries {\n");
    out.push_str("        let sub = encode_event(&delivery.event);\n");
    out.push_str("        let row = js_sys::Array::new();\n");
    out.push_str("        row.push(&JsValue::from_f64(delivery.listener_id.to_u64() as f64));\n");
    out.push_str("        for i in 0..sub.length() {\n");
    out.push_str("            row.push(&sub.get(i));\n");
    out.push_str("        }\n");
    out.push_str("        result.push(&row);\n");
    out.push_str("    }\n");
    out.push_str("    result\n");
    out.push_str("}\n");

    out
}

fn event_field_rust_type(typ: &str) -> String {
    match typ {
        "element_id" => "ElementId".to_string(),
        "string" => "String".to_string(),
        "f32" => "f32".to_string(),
        "f64" => "f64".to_string(),
        "u32" => "u32".to_string(),
        "usize" => "usize".to_string(),
        "bool" => "bool".to_string(),
        "pointer_kind" => "PointerKind".to_string(),
        other => panic!("unsupported event param type: {other}"),
    }
}

fn generate_event_types(proto: &Proto) -> String {
    let mut out = String::new();
    out.push_str(GENERATED_HEADER);
    out.push_str("use super::id::ElementId;\n");
    // Pull in any enum types referenced by event params (e.g. PointerKind on
    // pointer_move). Only emitted when an event actually uses the type so the
    // generated `use` never dangles.
    if proto
        .event_kinds
        .iter()
        .any(|ev| ev.params.iter().any(|p| p.typ == "pointer_kind"))
    {
        out.push_str("use super::pointer::PointerKind;\n");
    }
    out.push('\n');

    out.push_str("/// Semantic interaction events (ADR-0031).\n");
    out.push_str("#[derive(Clone, Debug)]\n");
    out.push_str("pub enum Event {\n");
    for ev in &proto.event_kinds {
        if let Some(desc) = &ev.description {
            for line in desc.lines() {
                out.push_str(&format!("    /// {}\n", line));
            }
        }
        let variant = to_pascal(&ev.name);
        if ev.params.is_empty() {
            out.push_str(&format!("    {},\n", variant));
        } else {
            out.push_str(&format!("    {} {{\n", variant));
            for p in &ev.params {
                out.push_str(&format!(
                    "        {}: {},\n",
                    p.name,
                    event_field_rust_type(&p.typ)
                ));
            }
            out.push_str("    },\n");
        }
    }
    out.push_str("}\n\n");

    let doc_events: Vec<_> = proto
        .event_kinds
        .iter()
        .filter(|ev| ev.document_runtime)
        .collect();

    out.push_str("/// Event kinds registerable via `register_listener`.\n");
    out.push_str("#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash)]\n");
    out.push_str("pub enum DocumentEventKind {\n");
    for ev in &doc_events {
        out.push_str(&format!("    {},\n", to_pascal(&ev.name)));
    }
    out.push_str("}\n\n");

    out.push_str("impl DocumentEventKind {\n");
    out.push_str("    pub fn bubbles(self) -> bool {\n");
    out.push_str("        match self {\n");
    for ev in &doc_events {
        let arm = if ev.bubbles { "true" } else { "false" };
        out.push_str(&format!(
            "            Self::{} => {},\n",
            to_pascal(&ev.name),
            arm
        ));
    }
    out.push_str("        }\n");
    out.push_str("    }\n\n");

    out.push_str("    pub fn from_u32(value: u32) -> Option<Self> {\n");
    out.push_str("        match value {\n");
    for ev in &doc_events {
        out.push_str(&format!(
            "            {} => Some(Self::{}),\n",
            ev.value,
            to_pascal(&ev.name)
        ));
    }
    out.push_str("            _ => None,\n");
    out.push_str("        }\n");
    out.push_str("    }\n");
    out.push_str("}\n\n");

    out.push_str("/// Map a runtime `Event` to its document kind, if registerable.\n");
    out.push_str("pub fn event_document_kind(event: &Event) -> Option<DocumentEventKind> {\n");
    out.push_str("    match event {\n");
    for ev in &doc_events {
        out.push_str(&format!(
            "        {} => Some(DocumentEventKind::{}),\n",
            event_match_wildcard(ev),
            to_pascal(&ev.name)
        ));
    }
    out.push_str("        _ => None,\n");
    out.push_str("    }\n");
    out.push_str("}\n");

    out
}

fn generate_pseudo_state_tables(proto: &Proto) -> String {
    let mut out = String::new();
    out.push_str(GENERATED_HEADER);
    out.push_str("use super::PseudoState;\n\n");

    out.push_str("pub fn pseudo_state_from_u32(v: u32) -> Option<PseudoState> {\n");
    out.push_str("    match v {\n");
    for ps in &proto.pseudo_states {
        out.push_str(&format!(
            "        {} => Some(PseudoState::{}),\n",
            ps.value,
            to_pascal(&ps.name)
        ));
    }
    out.push_str("        _ => None,\n");
    out.push_str("    }\n");
    out.push_str("}\n\n");

    let mut resolve_order: Vec<&PseudoStateEntry> = proto.pseudo_states.iter().collect();
    resolve_order.sort_by_key(|ps| ps.priority);

    out.push_str("/// Application order for `resolve_visual` (ascending priority; last wins).\n");
    out.push_str("pub const PSEUDO_RESOLVE_ORDER: [PseudoState; ");
    out.push_str(&resolve_order.len().to_string());
    out.push_str("] = [\n");
    for ps in &resolve_order {
        out.push_str(&format!("    PseudoState::{},\n", to_pascal(&ps.name)));
    }
    out.push_str("];\n\n");

    out.push_str("pub fn pseudo_state_css_suffix(state: PseudoState) -> &'static str {\n");
    out.push_str("    match state {\n");
    for ps in &proto.pseudo_states {
        out.push_str(&format!(
            "        PseudoState::{} => \"{}\",\n",
            to_pascal(&ps.name),
            ps.css_pseudo
        ));
    }
    out.push_str("    }\n");
    out.push_str("}\n\n");

    out.push_str("pub fn pseudo_state_css_priority(state: PseudoState) -> u32 {\n");
    out.push_str("    match state {\n");
    for ps in &proto.pseudo_states {
        out.push_str(&format!(
            "        PseudoState::{} => {},\n",
            to_pascal(&ps.name),
            ps.priority
        ));
    }
    out.push_str("    }\n");
    out.push_str("}\n");

    out
}

/// Element-kind tables consumed by `hayate_core` (`element/kind.rs`). The single
/// source for the UA default cursor per element-kind (ADR-0105): Canvas resolves
/// it through `resolve_cursor`, the DOM renderer reads the parallel TS table, and
/// neither renderer re-declares the mapping.
fn generate_element_kind_tables(proto: &Proto) -> String {
    let mut out = String::new();
    out.push_str(GENERATED_HEADER);
    out.push_str("use super::{CursorValue, ElementKind, UserSelectValue};\n\n");

    out.push_str(
        "/// UA default cursor for `kind` when no explicit `cursor` is set (ADR-0105).\n",
    );
    out.push_str("pub fn default_cursor(kind: ElementKind) -> CursorValue {\n");
    out.push_str("    match kind {\n");
    for ek in &proto.element_kinds {
        if let Some(cursor) = &ek.default_cursor {
            out.push_str(&format!(
                "        ElementKind::{} => CursorValue::{},\n",
                to_pascal(&ek.name),
                to_pascal(cursor)
            ));
        }
    }
    out.push_str("        _ => CursorValue::Default,\n");
    out.push_str("    }\n");
    out.push_str("}\n\n");

    out.push_str(
        "/// UA default `user-select` for `kind` when no explicit `user-select` is set\n\
         /// (ADR-0108). Single source for Canvas/DOM kind-default selectability.\n",
    );
    out.push_str("pub fn default_user_select(kind: ElementKind) -> UserSelectValue {\n");
    out.push_str("    match kind {\n");
    for ek in &proto.element_kinds {
        if let Some(user_select) = &ek.default_user_select {
            out.push_str(&format!(
                "        ElementKind::{} => UserSelectValue::{},\n",
                to_pascal(&ek.name),
                to_pascal(user_select)
            ));
        }
    }
    out.push_str("        _ => UserSelectValue::None,\n");
    out.push_str("    }\n");
    out.push_str("}\n\n");

    let editable: Vec<String> = proto
        .element_kinds
        .iter()
        .filter(|k| k.accepts_text_input)
        .map(|k| format!("ElementKind::{}", to_pascal(&k.name)))
        .collect();
    out.push_str(
        "/// Whether `kind` accepts text entry and so surfaces the platform soft\n\
         /// keyboard / IME when focused (#392).\n",
    );
    out.push_str("pub fn accepts_text_input(kind: ElementKind) -> bool {\n");
    if editable.is_empty() {
        out.push_str("    let _ = kind;\n    false\n");
    } else {
        out.push_str("    matches!(\n        kind,\n        ");
        out.push_str(&editable.join("\n            | "));
        out.push_str("\n    )\n");
    }
    out.push_str("}\n");

    out
}

#[cfg(test)]
mod generator_tests {
    use super::*;
    use std::path::Path;

    #[test]
    fn classify_all_style_tags_from_spec() {
        let spec_dir = Path::new(env!("CARGO_MANIFEST_DIR")).join("../spec");
        let proto = load_spec(&spec_dir);
        assert!(!proto.style_tags.is_empty());
        for tag in &proto.style_tags {
            let _ = ValueType::classify(tag);
        }
    }
}

/// Convert SCREAMING_SNAKE_CASE to PascalCase.
fn to_pascal(s: &str) -> String {
    s.split('_')
        .map(|word| {
            let mut c = word.chars();
            match c.next() {
                None => String::new(),
                Some(f) => f.to_uppercase().collect::<String>() + &c.as_str().to_lowercase(),
            }
        })
        .collect()
}
