use std::fs;
use std::path::Path;

use serde::Deserialize;

const GENERATED_HEADER: &str = "// AUTO-GENERATED by Hayate/proto/generator — DO NOT EDIT\n// Source: proto/spec/*.json\n\n";

/// Generate protocol.rs, dispatch.rs, dom_style_mapper.rs, and event_types.rs into `out_dir`.
pub fn generate_all(spec_dir: &Path, out_dir: &Path) {
    fs::create_dir_all(out_dir).expect("cannot create output directory");

    let proto = load_spec(spec_dir);
    let code = generate(&proto);
    let codec = generate_codec(&proto);
    let dispatch = generate_dispatch(&proto);
    let dom_mapper = generate_dom_style_mapper(&proto);
    let event_types = generate_event_types(&proto);

    fs::write(out_dir.join("protocol.rs"), code).unwrap();
    fs::write(out_dir.join("codec.rs"), codec).unwrap();
    fs::write(out_dir.join("dispatch.rs"), dispatch).unwrap();
    fs::write(out_dir.join("dom_style_mapper.rs"), dom_mapper).unwrap();
    fs::write(out_dir.join("event_types.rs"), event_types).unwrap();
}

// ---------------------------------------------------------------------------
// Data model
// ---------------------------------------------------------------------------

#[derive(Default)]
struct Proto {
    types: Vec<TypeDef>,
    enums: Vec<EnumDef>,
    opcodes: Vec<Entry>,
    style_tags: Vec<Entry>,
    event_kinds: Vec<Entry>,
    element_kinds: Vec<SimpleEntry>,
    unset_kinds: Vec<SimpleEntry>,
    modifier_keys: Vec<SimpleEntry>,
}

#[derive(Default)]
struct TypeDef {
    name: String,
    #[allow(dead_code)]
    raw_slots: usize,
    fields: Vec<Param>,
}

#[derive(Default)]
struct EnumDef {
    name: String,
    #[allow(dead_code)]
    string_values: bool,
    values: Vec<EnumValue>,
}

#[derive(Default, Clone)]
struct EnumValue {
    name: String,
    value: String, // numeric string or quoted string
}

#[derive(Default)]
struct Entry {
    name: String,
    value: u32,
    variable_length: bool,
    params: Vec<Param>,
    #[allow(dead_code)]
    encode_from: Option<String>,
    wire_role: Option<String>,
    adapter_tier: Option<String>,
    document_runtime: bool,
    bubbles: bool,
    #[allow(dead_code)]
    interaction_kind: Option<String>,
    description: Option<String>,
}

#[derive(Default, Clone)]
struct Param {
    name: String,
    typ: String,
    count: usize, // 0 means 1 (no count attribute)
}

#[derive(Default)]
struct SimpleEntry {
    name: String,
    value: u32,
}

// ---------------------------------------------------------------------------
// JSON spec loader (proto/spec/*.json)
// ---------------------------------------------------------------------------

#[derive(Deserialize)]
struct ParamJson {
    name: String,
    #[serde(rename = "type")]
    typ: String,
    #[serde(default)]
    count: usize,
}

#[derive(Deserialize)]
struct EntryJson {
    name: String,
    value: u32,
    #[serde(default)]
    variable_length: bool,
    #[serde(default)]
    params: Vec<ParamJson>,
    #[serde(default, rename = "encodeFrom")]
    encode_from: Option<String>,
    #[serde(default, rename = "wireRole")]
    wire_role: Option<String>,
    #[serde(default, rename = "adapterTier")]
    adapter_tier: Option<String>,
    #[serde(default, rename = "documentRuntime")]
    document_runtime: bool,
    #[serde(default)]
    bubbles: bool,
    #[serde(default, rename = "interactionKind")]
    interaction_kind: Option<String>,
    #[serde(default)]
    description: Option<String>,
}

#[derive(Deserialize)]
struct TypeJson {
    name: String,
    raw_slots: usize,
    fields: Vec<ParamJson>,
}

#[derive(Deserialize)]
struct EnumValueJson {
    name: String,
    value: serde_json::Value,
}

#[derive(Deserialize)]
struct EnumJson {
    name: String,
    #[serde(default)]
    string_values: bool,
    values: Vec<EnumValueJson>,
}

#[derive(Deserialize)]
struct SimpleJson {
    name: String,
    value: u32,
}

fn read_json<T: for<'de> Deserialize<'de>>(spec_dir: &Path, name: &str) -> T {
    let path = spec_dir.join(name);
    let text = fs::read_to_string(&path)
        .unwrap_or_else(|e| panic!("cannot read {}: {}", path.display(), e));
    serde_json::from_str(&text)
        .unwrap_or_else(|e| panic!("invalid JSON in {}: {}", path.display(), e))
}

fn enum_value_string(value: &serde_json::Value) -> String {
    match value {
        serde_json::Value::Number(n) => n.to_string(),
        serde_json::Value::String(s) => s.clone(),
        other => panic!("invalid enum value: {other}"),
    }
}

fn load_spec(spec_dir: &Path) -> Proto {
    let types: Vec<TypeJson> = read_json(spec_dir, "types.json");
    let enums: Vec<EnumJson> = read_json(spec_dir, "enums.json");
    let opcodes: Vec<EntryJson> = read_json(spec_dir, "opcodes.json");
    let style_tags: Vec<EntryJson> = read_json(spec_dir, "style_tags.json");
    let event_kinds: Vec<EntryJson> = read_json(spec_dir, "event_kinds.json");
    let element_kinds: Vec<SimpleJson> = read_json(spec_dir, "element_kinds.json");
    let unset_kinds: Vec<SimpleJson> = read_json(spec_dir, "unset_kinds.json");
    let modifier_keys: Vec<SimpleJson> = read_json(spec_dir, "modifier_keys.json");

    Proto {
        types: types
            .into_iter()
            .map(|t| TypeDef {
                name: t.name,
                raw_slots: t.raw_slots,
                fields: t
                    .fields
                    .into_iter()
                    .map(|f| Param {
                        name: f.name,
                        typ: f.typ,
                        count: f.count,
                    })
                    .collect(),
            })
            .collect(),
        enums: enums
            .into_iter()
            .map(|e| EnumDef {
                name: e.name,
                string_values: e.string_values,
                values: e
                    .values
                    .into_iter()
                    .map(|v| EnumValue {
                        name: v.name,
                        value: enum_value_string(&v.value),
                    })
                    .collect(),
            })
            .collect(),
        opcodes: entries_from_json(opcodes),
        style_tags: entries_from_json(style_tags),
        event_kinds: entries_from_json(event_kinds),
        element_kinds: simple_from_json(element_kinds),
        unset_kinds: simple_from_json(unset_kinds),
        modifier_keys: simple_from_json(modifier_keys),
    }
}

fn entries_from_json(entries: Vec<EntryJson>) -> Vec<Entry> {
    entries
        .into_iter()
        .map(|e| Entry {
            name: e.name,
            value: e.value,
            variable_length: e.variable_length,
            params: e
                .params
                .into_iter()
                .map(|p| Param {
                    name: p.name,
                    typ: p.typ,
                    count: p.count,
                })
                .collect(),
            encode_from: e.encode_from,
            wire_role: e.wire_role,
            adapter_tier: e.adapter_tier,
            document_runtime: e.document_runtime,
            bubbles: e.bubbles,
            interaction_kind: e.interaction_kind,
            description: e.description,
        })
        .collect()
}

fn simple_from_json(entries: Vec<SimpleJson>) -> Vec<SimpleEntry> {
    entries
        .into_iter()
        .map(|e| SimpleEntry {
            name: e.name,
            value: e.value,
        })
        .collect()
}

// ---------------------------------------------------------------------------
// Code generator
// ---------------------------------------------------------------------------

fn param_slots(p: &Param) -> usize {
    let count = if p.count == 0 { 1 } else { p.count };
    count
}

fn param_rust_type(typ: &str, count: usize) -> String {
    let base = match typ {
        "element_id" => "u64",
        "u32" => "u32",
        "f32" => "f32",
        "f64" => "f64",
        "bool" => "bool",
        "usize" => "usize",
        "string" => "String",
        other => other, // enums etc. – not used in Op/StyleTag
    };
    if count > 1 {
        format!("[{}; {}]", base, count)
    } else {
        base.to_string()
    }
}

fn generate(proto: &Proto) -> String {
    let mut out = String::new();

    out.push_str(GENERATED_HEADER);

    // OP_* constants
    out.push_str("// Opcode constants\n");
    for op in &proto.opcodes {
        out.push_str(&format!(
            "pub const OP_{}: u32 = {};\n",
            op.name, op.value
        ));
    }
    out.push('\n');

    // OP_SLOTS
    out.push_str("// Payload slot counts per opcode (op discriminant excluded)\n");
    out.push_str("pub const OP_SLOTS: &[usize] = &[\n");
    for op in &proto.opcodes {
        let slots: usize = op.params.iter().map(param_slots).sum();
        out.push_str(&format!(
            "    {}, // {}\n",
            slots, op.name
        ));
    }
    out.push_str("];\n\n");

    // TAG_* constants
    out.push_str("// Style tag constants\n");
    for tag in &proto.style_tags {
        out.push_str(&format!(
            "pub const TAG_{}: u32 = {};\n",
            tag.name, tag.value
        ));
    }
    out.push('\n');

    // EVENT_KIND_* constants (f64)
    out.push_str("// Event kind constants\n");
    for ev in &proto.event_kinds {
        out.push_str(&format!(
            "pub const EVENT_KIND_{}: f64 = {}.0;\n",
            ev.name.to_uppercase(),
            ev.value
        ));
    }
    out.push('\n');

    out.push_str("// Event wire metadata (from event_kinds.json)\n");
    for ev in &proto.event_kinds {
        let wire_role = ev
            .wire_role
            .as_deref()
            .unwrap_or_else(|| panic!("event_kinds.{}: missing wireRole", ev.name));
        let adapter_tier = ev
            .adapter_tier
            .as_deref()
            .unwrap_or_else(|| panic!("event_kinds.{}: missing adapterTier", ev.name));
        out.push_str(&format!(
            "pub const EVENT_WIRE_ROLE_{}: &str = \"{}\";\n",
            ev.name.to_uppercase(),
            wire_role
        ));
        out.push_str(&format!(
            "pub const EVENT_ADAPTER_TIER_{}: &str = \"{}\";\n",
            ev.name.to_uppercase(),
            adapter_tier
        ));
    }
    out.push('\n');

    // ELEMENT_KIND_* constants
    out.push_str("// Element kind constants\n");
    for ek in &proto.element_kinds {
        out.push_str(&format!(
            "pub const ELEMENT_KIND_{}: u32 = {};\n",
            ek.name.to_uppercase(),
            ek.value
        ));
    }
    out.push('\n');

    // UNSET_KIND_* constants
    out.push_str("// Unset kind constants\n");
    for uk in &proto.unset_kinds {
        out.push_str(&format!(
            "pub const UNSET_KIND_{}: u32 = {};\n",
            uk.name.to_uppercase(),
            uk.value
        ));
    }
    out.push('\n');

    // MODIFIER_* constants
    out.push_str("// Modifier key constants\n");
    for mk in &proto.modifier_keys {
        out.push_str(&format!(
            "pub const MODIFIER_{}: u32 = {};\n",
            mk.name.to_uppercase(),
            mk.value
        ));
    }
    out.push('\n');

    // Op enum
    out.push_str("// Op enum\n");
    out.push_str("#[derive(Debug, Clone)]\n");
    out.push_str("pub enum Op {\n");
    for op in &proto.opcodes {
        // Convert SNAKE_UPPER to PascalCase
        let variant = to_pascal(&op.name);
        if op.params.is_empty() {
            out.push_str(&format!("    {},\n", variant));
        } else {
            out.push_str(&format!("    {} {{\n", variant));
            for p in &op.params {
                let count = if p.count == 0 { 1 } else { p.count };
                let rust_ty = param_rust_type(&p.typ, count);
                out.push_str(&format!("        {}: {},\n", p.name, rust_ty));
            }
            out.push_str("    },\n");
        }
    }
    out.push_str("}\n\n");

    // parse_next_op
    out.push_str("pub fn parse_next_op(ops: &[f64], i: usize) -> Result<(Op, usize), &'static str> {\n");
    out.push_str("    if i >= ops.len() { return Err(\"unexpected end of ops\"); }\n");
    out.push_str("    let disc = ops[i] as u32;\n");
    out.push_str("    let i = i + 1;\n");
    out.push_str("    match disc {\n");
    for op in &proto.opcodes {
        let variant = to_pascal(&op.name);
        let total_slots: usize = op.params.iter().map(param_slots).sum();
        out.push_str(&format!("        {} => {{\n", op.value));
        out.push_str(&format!(
            "            if i + {} > ops.len() {{ return Err(\"op {} truncated\"); }}\n",
            total_slots, op.name
        ));
        let mut slot = 0usize;
        for p in &op.params {
            let count = if p.count == 0 { 1 } else { p.count };
            if count > 1 {
                out.push_str(&format!("            let mut {} = [0f64; {}];\n", p.name, count));
                for ci in 0..count {
                    out.push_str(&format!(
                        "            {}[{}] = ops[i + {}];\n",
                        p.name,
                        ci,
                        slot + ci
                    ));
                }
            } else {
                let cast = match p.typ.as_str() {
                    "element_id" => "ops[i + IDX] as u64",
                    "u32" => "ops[i + IDX] as u32",
                    "f32" => "ops[i + IDX] as f32",
                    "f64" => "ops[i + IDX]",
                    "bool" => "ops[i + IDX] != 0.0",
                    "usize" => "ops[i + IDX] as usize",
                    _ => "ops[i + IDX] as u64",
                };
                let cast = cast.replace("IDX", &slot.to_string());
                out.push_str(&format!("            let {} = {};\n", p.name, cast));
            }
            slot += count;
        }
        if op.params.is_empty() {
            out.push_str(&format!("            Ok((Op::{}, i))\n", variant));
        } else {
            let field_list: Vec<String> = op.params.iter().map(|p| p.name.clone()).collect();
            out.push_str(&format!(
                "            Ok((Op::{} {{ {} }}, i + {}))\n",
                variant,
                field_list.join(", "),
                total_slots
            ));
        }
        out.push_str("        }\n");
    }
    out.push_str("        _ => Err(\"unknown opcode\"),\n");
    out.push_str("    }\n");
    out.push_str("}\n\n");

    // StyleTag enum
    out.push_str("// StyleTag enum\n");
    out.push_str("#[derive(Debug, Clone)]\n");
    out.push_str("pub enum StyleTag {\n");
    for tag in &proto.style_tags {
        let variant = to_pascal(&tag.name);
        if tag.params.is_empty() {
            out.push_str(&format!("    {},\n", variant));
        } else {
            // flatten compound types to raw f32
            let fields = flatten_tag_params(&tag.params, proto);
            if fields.is_empty() {
                out.push_str(&format!("    {},\n", variant));
            } else {
                out.push_str(&format!("    {} {{\n", variant));
                for (fname, ftype) in &fields {
                    out.push_str(&format!("        {}: {},\n", fname, ftype));
                }
                out.push_str("    },\n");
            }
        }
    }
    out.push_str("}\n\n");

    // parse_next_style_tag
    out.push_str("pub fn parse_next_style_tag(packed: &[f32], i: usize) -> Result<(StyleTag, usize), &'static str> {\n");
    out.push_str("    if i >= packed.len() { return Err(\"unexpected end of style data\"); }\n");
    out.push_str("    let tag = packed[i] as u32;\n");
    out.push_str("    let i = i + 1;\n");
    out.push_str("    match tag {\n");
    for tag in &proto.style_tags {
        let variant = to_pascal(&tag.name);
        let fields = flatten_tag_params(&tag.params, proto);
        let slot_count = fields.len();
        out.push_str(&format!("        {} => {{\n", tag.value));
        if tag.variable_length {
            // string: [byte_len, byte0, byte1, …] — one UTF-8 byte per f32 slot (wire format)
            out.push_str("            if i >= packed.len() { return Err(\"style tag string truncated\"); }\n");
            out.push_str("            let byte_len = packed[i] as usize;\n");
            out.push_str("            if i + 1 + byte_len > packed.len() { return Err(\"style tag string data truncated\"); }\n");
            out.push_str("            let bytes: Vec<u8> = (0..byte_len).map(|j| packed[i + 1 + j] as u8).collect();\n");
            out.push_str("            let family = String::from_utf8(bytes).map_err(|_| \"invalid utf8 in font family\")?;\n");
            out.push_str(&format!(
                "            Ok((StyleTag::{} {{ family }}, i + 1 + byte_len))\n",
                variant
            ));
        } else if fields.is_empty() {
            out.push_str(&format!("            Ok((StyleTag::{}, i))\n", variant));
        } else {
            out.push_str(&format!(
                "            if i + {} > packed.len() {{ return Err(\"style tag {} truncated\"); }}\n",
                slot_count, tag.name
            ));
            let mut si = 0usize;
            for (fname, _ftype) in &fields {
                out.push_str(&format!(
                    "            let {} = packed[i + {}];\n",
                    fname, si
                ));
                si += 1;
            }
            let field_list: Vec<String> = fields.iter().map(|(n, _)| n.clone()).collect();
            out.push_str(&format!(
                "            Ok((StyleTag::{} {{ {} }}, i + {}))\n",
                variant,
                field_list.join(", "),
                slot_count
            ));
        }
        out.push_str("        }\n");
    }
    out.push_str("        _ => Err(\"unknown style tag\"),\n");
    out.push_str("    }\n");
    out.push_str("}\n\n");

    out.push_str(&generate_style_codec(proto));
    out.push_str(&generate_encode_event(proto));

    out
}

fn generate_style_codec(proto: &Proto) -> String {
    let mut out = String::new();

    out.push_str("// ── Style packet codec (generated) ─────────────────────────────────────\n\n");
    out.push_str("use hayate_core::{\n");
    out.push_str("    AlignValue, Color, Dimension, DimensionUnit, DisplayValue, FlexDirectionValue,\n");
    out.push_str("    JustifyValue, StyleProp,\n");
    out.push_str("};\n");
    out.push_str("use wasm_bindgen::prelude::*;\n\n");

    out.push_str("fn codec_dim(value: f32, unit_raw: f32) -> Dimension {\n");
    out.push_str("    let unit = match unit_raw as u32 {\n");
    out.push_str("        0 => DimensionUnit::Px,\n");
    out.push_str("        1 => DimensionUnit::Percent,\n");
    out.push_str("        2 => DimensionUnit::Auto,\n");
    out.push_str("        3 => DimensionUnit::Fr,\n");
    out.push_str("        _ => DimensionUnit::Px,\n");
    out.push_str("    };\n");
    out.push_str("    Dimension { value, unit }\n");
    out.push_str("}\n\n");

    out.push_str("fn codec_color(r: f32, g: f32, b: f32, a: f32) -> Color {\n");
    out.push_str("    Color::new(r as f64, g as f64, b as f64, a as f64)\n");
    out.push_str("}\n\n");

    for en in &proto.enums {
        let rust_enum = match en.name.as_str() {
            "display" => "DisplayValue",
            "flex_direction" => "FlexDirectionValue",
            "align_items" => "AlignValue",
            "justify_content" => "JustifyValue",
            _ => continue,
        };
        let fn_name = format!("codec_{}", en.name);
        out.push_str(&format!("fn {fn_name}(raw: f32) -> {rust_enum} {{\n"));
        out.push_str("    match raw as u32 {\n");
        for v in &en.values {
            let variant = to_pascal(&v.name);
            out.push_str(&format!(
                "        {} => {rust_enum}::{variant},\n",
                v.value
            ));
        }
        let default_variant = to_pascal(&en.values[0].name);
        out.push_str(&format!("        _ => {rust_enum}::{default_variant},\n"));
        out.push_str("    }\n");
        out.push_str("}\n\n");
    }

    out.push_str("fn style_tag_to_prop(tag: StyleTag) -> Result<StyleProp, JsValue> {\n");
    out.push_str("    Ok(match tag {\n");
    for tag in &proto.style_tags {
        let variant = to_pascal(&tag.name);
        let prop_variant = to_pascal(&tag.name);
        out.push_str(&format!("        StyleTag::{variant}"));
        let fields = flatten_tag_params(&tag.params, proto);
        if fields.is_empty() {
            out.push_str(" => ");
        } else {
            let field_names: Vec<String> = fields.iter().map(|(n, _)| n.clone()).collect();
            out.push_str(&format!(" {{ {} }} => ", field_names.join(", ")));
        }
        let expr = style_tag_to_prop_expr(&tag.name, &tag.params, proto);
        out.push_str(&format!("StyleProp::{prop_variant}({expr}),\n"));
    }
    out.push_str("    })\n");
    out.push_str("}\n\n");

    out.push_str(
        "pub fn decode_style_packet(packed: &[f32]) -> Result<Vec<StyleProp>, JsValue> {\n",
    );
    out.push_str("    let mut out = Vec::new();\n");
    out.push_str("    let mut i = 0usize;\n");
    out.push_str("    while i < packed.len() {\n");
    out.push_str("        let (tag, next) = parse_next_style_tag(packed, i)\n");
    out.push_str("            .map_err(|e| JsValue::from_str(e))?;\n");
    out.push_str("        i = next;\n");
    out.push_str("        out.push(style_tag_to_prop(tag)?);\n");
    out.push_str("    }\n");
    out.push_str("    Ok(out)\n");
    out.push_str("}\n\n");

    out
}

fn generate_codec(proto: &Proto) -> String {
    let mut out = String::new();
    out.push_str(GENERATED_HEADER);
    out.push_str("// ── Wire codec encode (generated) ────────────────────────────────────────\n\n");

    out.push_str("fn encode_dim_unit(unit: DimensionUnit) -> f32 {\n");
    out.push_str("    match unit {\n");
    out.push_str("        DimensionUnit::Px => 0.0,\n");
    out.push_str("        DimensionUnit::Percent => 1.0,\n");
    out.push_str("        DimensionUnit::Auto => 2.0,\n");
    out.push_str("        DimensionUnit::Fr => 3.0,\n");
    out.push_str("    }\n");
    out.push_str("}\n\n");

    for en in &proto.enums {
        let rust_enum = match en.name.as_str() {
            "display" => "DisplayValue",
            "flex_direction" => "FlexDirectionValue",
            "align_items" => "AlignValue",
            "justify_content" => "JustifyValue",
            _ => continue,
        };
        let fn_name = format!("encode_{}", en.name);
        out.push_str(&format!("fn {fn_name}(value: {rust_enum}) -> f32 {{\n"));
        out.push_str("    match value {\n");
        for v in &en.values {
            let variant = to_pascal(&v.name);
            out.push_str(&format!(
                "        {rust_enum}::{variant} => {}.0,\n",
                v.value
            ));
        }
        out.push_str("    }\n");
        out.push_str("}\n\n");
    }

    out.push_str("pub fn encode_op(buf: &mut Vec<f64>, op: &Op) {\n");
    out.push_str("    match op {\n");
    for op in &proto.opcodes {
        let variant = to_pascal(&op.name);
        if op.params.is_empty() {
            out.push_str(&format!("        Op::{variant} => buf.push(OP_{} as f64),\n", op.name));
            continue;
        }
        let fields: Vec<String> = op.params.iter().map(|p| p.name.clone()).collect();
        out.push_str(&format!(
            "        Op::{variant} {{ {} }} => {{\n",
            fields.join(", ")
        ));
        out.push_str(&format!("            buf.push(OP_{} as f64);\n", op.name));
        for p in &op.params {
            let count = if p.count == 0 { 1 } else { p.count };
            if count > 1 {
                out.push_str(&format!("            for slot in {name}.iter() {{\n", name = p.name));
                out.push_str("                buf.push(*slot);\n");
                out.push_str("            }\n");
            } else {
                let push = match p.typ.as_str() {
                    "element_id" | "u32" | "usize" => format!("buf.push(*{name} as f64);", name = p.name),
                    "f32" => format!("buf.push(*{name} as f64);", name = p.name),
                    "f64" => format!("buf.push(*{name});", name = p.name),
                    "bool" => format!("buf.push(if *{name} {{ 1.0 }} else {{ 0.0 }});", name = p.name),
                    other => panic!("unsupported op param type for encode: {other}"),
                };
                out.push_str(&format!("            {push}\n"));
            }
        }
        out.push_str("        }\n");
    }
    out.push_str("    }\n");
    out.push_str("}\n\n");

    out.push_str("pub fn encode_style_packet(buf: &mut Vec<f32>, props: &[StyleProp]) {\n");
    out.push_str("    for prop in props {\n");
    out.push_str("        match prop {\n");
    for tag in &proto.style_tags {
        let prop_variant = to_pascal(&tag.name);
        let binding = style_prop_encode_binding(&tag.name, &tag.params);
        out.push_str(&format!("            StyleProp::{prop_variant}{binding} => {{\n"));
        out.push_str(&format!("                buf.push(TAG_{} as f32);\n", tag.name));
        out.push_str(&style_prop_encode_body(&tag.name, &tag.params));
        out.push_str("            }\n");
    }
    out.push_str("        }\n");
    out.push_str("    }\n");
    out.push_str("}\n");

    out
}

fn style_prop_encode_binding(tag_name: &str, params: &[Param]) -> String {
    if tag_name == "FONT_FAMILY" {
        return "(f)".to_string();
    }
    if tag_name == "Z_INDEX" {
        return "(z)".to_string();
    }
    for p in params {
        match p.typ.as_str() {
            "color" => return "(c)".to_string(),
            "dimension" => return "(d)".to_string(),
            "display" | "flex_direction" | "align_items" | "justify_content" | "f32" => {
                return "(v)".to_string();
            }
            _ => {}
        }
    }
    "(v)".to_string()
}

fn style_prop_encode_body(tag_name: &str, params: &[Param]) -> String {
    if tag_name == "FONT_FAMILY" {
        return "                let bytes = f.as_bytes();\n\
                buf.push(bytes.len() as f32);\n\
                for byte in bytes {\n\
                    buf.push(*byte as f32);\n\
                }\n"
            .to_string();
    }
    if tag_name == "Z_INDEX" {
        return "                buf.push(*z as f32);\n".to_string();
    }
    for p in params {
        match p.typ.as_str() {
            "color" => {
                return "                let arr = c.to_array_f32();\n\
                buf.extend_from_slice(&arr);\n"
                    .to_string();
            }
            "dimension" => {
                return "                buf.push(d.value);\n\
                buf.push(encode_dim_unit(d.unit));\n"
                    .to_string();
            }
            "display" => return "                buf.push(encode_display(*v));\n".to_string(),
            "flex_direction" => {
                return "                buf.push(encode_flex_direction(*v));\n".to_string();
            }
            "align_items" => return "                buf.push(encode_align_items(*v));\n".to_string(),
            "justify_content" => {
                return "                buf.push(encode_justify_content(*v));\n".to_string();
            }
            "f32" => return "                buf.push(*v);\n".to_string(),
            _ => {}
        }
    }
    "                buf.push(*v);\n".to_string()
}

fn generate_dom_style_mapper(proto: &Proto) -> String {
    let mut out = String::new();

    out.push_str(GENERATED_HEADER);
    out.push_str("// ── Hayate CSS → browser CSS mapper (generated) ─────────────────────────\n\n");
    out.push_str("use web_sys::CssStyleDeclaration;\n\n");

    out.push_str("fn dom_css_dim(d: Dimension) -> String {\n");
    out.push_str("    match d.unit {\n");
    out.push_str("        DimensionUnit::Px => format!(\"{}px\", d.value),\n");
    out.push_str("        DimensionUnit::Percent => format!(\"{}%\", d.value),\n");
    out.push_str("        DimensionUnit::Auto => \"auto\".into(),\n");
    out.push_str("        DimensionUnit::Fr => format!(\"{}fr\", d.value),\n");
    out.push_str("    }\n");
    out.push_str("}\n\n");

    out.push_str("fn dom_css_rgba(c: Color) -> String {\n");
    out.push_str("    let arr = c.to_array_f32();\n");
    out.push_str("    format!(\n");
    out.push_str("        \"rgba({},{},{},{})\",\n");
    out.push_str("        (arr[0] * 255.0) as u8,\n");
    out.push_str("        (arr[1] * 255.0) as u8,\n");
    out.push_str("        (arr[2] * 255.0) as u8,\n");
    out.push_str("        arr[3],\n");
    out.push_str("    )\n");
    out.push_str("}\n\n");

    out.push_str(
        "pub fn apply_style_prop_to_dom(style: &CssStyleDeclaration, prop: &StyleProp) -> Result<(), JsValue> {\n",
    );
    out.push_str("    match *prop {\n");

    for tag in &proto.style_tags {
        let variant = to_pascal(&tag.name);
        let css_prop = patch_key_to_kebab(&tag_to_patch_key(&tag.name));
        let (binding, value_var) = style_prop_match_binding(&tag.name, &tag.params);

        out.push_str(&format!("        StyleProp::{variant}{binding} => {{\n"));
        let body = dom_apply_body(&tag.name, &tag.params, &css_prop, value_var);
        for line in body.lines() {
            out.push_str(&format!("            {line}\n"));
        }
        out.push_str("        }\n");
    }

    out.push_str("    }\n");
    out.push_str("    Ok(())\n");
    out.push_str("}\n");

    out
}

fn style_prop_match_binding(tag_name: &str, params: &[Param]) -> (String, &'static str) {
    if tag_name == "FONT_FAMILY" {
        return ("(ref f)".to_string(), "f");
    }
    if tag_name == "Z_INDEX" {
        return ("(z)".to_string(), "z");
    }
    for p in params {
        match p.typ.as_str() {
            "color" => return ("(c)".to_string(), "c"),
            "dimension" => return ("(d)".to_string(), "d"),
            "display" | "flex_direction" | "align_items" | "justify_content" => {
                return ("(v)".to_string(), "v");
            }
            "f32" => return ("(v)".to_string(), "v"),
            _ => {}
        }
    }
    ("(v)".to_string(), "v")
}

fn dom_apply_body(tag_name: &str, params: &[Param], css_prop: &str, value_var: &str) -> String {
    if tag_name == "FONT_FAMILY" {
        return format!("style.set_property(\"{css_prop}\", {value_var})?;");
    }
    if tag_name == "Z_INDEX" {
        return format!("style.set_property(\"{css_prop}\", &{value_var}.to_string())?;");
    }
    for p in params {
        match p.typ.as_str() {
            "color" => {
                return format!("style.set_property(\"{css_prop}\", &dom_css_rgba({value_var}))?;");
            }
            "dimension" => {
                return format!("style.set_property(\"{css_prop}\", &dom_css_dim({value_var}))?;");
            }
            "display" => {
                return format!(
                    "let s = match {value_var} {{\n\
                    DisplayValue::Flex => \"flex\",\n\
                    DisplayValue::Grid => \"grid\",\n\
                    DisplayValue::Block => \"block\",\n\
                    DisplayValue::None => \"none\",\n\
                }};\n\
                style.set_property(\"{css_prop}\", s)?;"
                );
            }
            "flex_direction" => {
                return format!(
                    "let s = match {value_var} {{\n\
                    FlexDirectionValue::Row => \"row\",\n\
                    FlexDirectionValue::Column => \"column\",\n\
                    FlexDirectionValue::RowReverse => \"row-reverse\",\n\
                    FlexDirectionValue::ColumnReverse => \"column-reverse\",\n\
                }};\n\
                style.set_property(\"{css_prop}\", s)?;"
                );
            }
            "align_items" => {
                return format!(
                    "let s = match {value_var} {{\n\
                    AlignValue::FlexStart => \"flex-start\",\n\
                    AlignValue::FlexEnd => \"flex-end\",\n\
                    AlignValue::Center => \"center\",\n\
                    AlignValue::Stretch => \"stretch\",\n\
                    AlignValue::Baseline => \"baseline\",\n\
                }};\n\
                style.set_property(\"{css_prop}\", s)?;"
                );
            }
            "justify_content" => {
                return format!(
                    "let s = match {value_var} {{\n\
                    JustifyValue::FlexStart => \"flex-start\",\n\
                    JustifyValue::FlexEnd => \"flex-end\",\n\
                    JustifyValue::Center => \"center\",\n\
                    JustifyValue::SpaceBetween => \"space-between\",\n\
                    JustifyValue::SpaceAround => \"space-around\",\n\
                    JustifyValue::SpaceEvenly => \"space-evenly\",\n\
                }};\n\
                style.set_property(\"{css_prop}\", s)?;"
                );
            }
            "f32" => match tag_name {
                "OPACITY" => {
                    return format!(
                        "style.set_property(\"{css_prop}\", &format!(\"{{}}\", {value_var}.clamp(0.0, 1.0)))?;"
                    );
                }
                "BORDER_RADIUS" | "FONT_SIZE" => {
                    return format!(
                        "style.set_property(\"{css_prop}\", &format!(\"{{}}px\", {value_var}.max(0.0)))?;"
                    );
                }
                "BORDER_WIDTH" => {
                    return format!(
                        "let w = {value_var}.max(0.0);\n\
                        style.set_property(\"{css_prop}\", &format!(\"{{}}px\", w))?;\n\
                        style.set_property(\"border-style\", if w > 0.0 {{ \"solid\" }} else {{ \"none\" }})?;"
                    );
                }
                "FONT_WEIGHT" => {
                    return format!(
                        "style.set_property(\"{css_prop}\", &format!(\"{{}}\", {value_var}.clamp(1.0, 1000.0)))?;"
                    );
                }
                "FLEX_GROW" => {
                    return format!(
                        "style.set_property(\"{css_prop}\", &format!(\"{{}}\", {value_var}.max(0.0)))?;"
                    );
                }
                _ => {
                    return format!(
                        "style.set_property(\"{css_prop}\", &format!(\"{{}}\", {value_var}))?;"
                    );
                }
            },
            _ => {}
        }
    }
    format!(
        "style.set_property(\"{css_prop}\", &format!(\"{{}}\", {value_var}))?;"
    )
}

fn tag_to_patch_key(s: &str) -> String {
    let lower = s.to_lowercase();
    let mut result = String::new();
    let mut capitalize_next = false;
    for ch in lower.chars() {
        if ch == '_' {
            capitalize_next = true;
        } else if capitalize_next {
            result.extend(ch.to_uppercase());
            capitalize_next = false;
        } else {
            result.push(ch);
        }
    }
    result
}

fn patch_key_to_kebab(s: &str) -> String {
    let mut out = String::new();
    for (i, ch) in s.chars().enumerate() {
        if ch.is_uppercase() {
            if i > 0 {
                out.push('-');
            }
            out.extend(ch.to_lowercase());
        } else {
            out.push(ch);
        }
    }
    out
}

fn style_tag_to_prop_expr(tag_name: &str, params: &[Param], _proto: &Proto) -> String {
    if tag_name == "FONT_FAMILY" {
        return "family".to_string();
    }
    if tag_name == "Z_INDEX" {
        return "value as i32".to_string();
    }
    for p in params {
        match p.typ.as_str() {
            "color" => {
                let prefix = &p.name;
                return format!(
                    "codec_color({prefix}_r, {prefix}_g, {prefix}_b, {prefix}_a)"
                );
            }
            "dimension" => return format!("codec_dim({}_value, {}_unit)", p.name, p.name),
            "display" => return "codec_display(value)".to_string(),
            "flex_direction" => return "codec_flex_direction(value)".to_string(),
            "align_items" => return "codec_align_items(value)".to_string(),
            "justify_content" => return "codec_justify_content(value)".to_string(),
            "f32" => return "value".to_string(),
            _ => {}
        }
    }
    if params.is_empty() {
        "()".to_string()
    } else {
        "value".to_string()
    }
}

fn generate_dispatch(proto: &Proto) -> String {
    let mut out = String::new();
    out.push_str(GENERATED_HEADER);
    out.push_str("use hayate_core::{ElementId, ElementKind, StylePropKind};\n");
    out.push_str("use wasm_bindgen::prelude::*;\n\n");
    out.push_str("use super::ApplyMutationsHost;\n");
    out.push_str("use crate::generated::{Op, decode_style_packet, parse_next_op};\n\n");

    out.push_str("pub(crate) fn unset_kind_from_u32(v: u32) -> Result<StylePropKind, JsValue> {\n");
    out.push_str("    match v {\n");
    for uk in &proto.unset_kinds {
        out.push_str(&format!(
            "        {} => Ok(StylePropKind::{}),\n",
            uk.value,
            to_pascal(&uk.name)
        ));
    }
    out.push_str(
        "        _ => Err(JsValue::from_str(&format!(\"unknown unset style kind {v}\"))),\n",
    );
    out.push_str("    }\n");
    out.push_str("}\n\n");

    out.push_str("pub(crate) fn apply_mutations_batch<H: ApplyMutationsHost>(\n");
    out.push_str("    host: &mut H,\n");
    out.push_str("    ops: &[f64],\n");
    out.push_str("    styles: &[f32],\n");
    out.push_str("    texts: &js_sys::Array,\n");
    out.push_str(") -> Result<(), JsValue> {\n");
    out.push_str("    let mut i = 0usize;\n");
    out.push_str("    while i < ops.len() {\n");
    out.push_str("        let (op, next) = parse_next_op(ops, i).map_err(|e| JsValue::from_str(e))?;\n");
    out.push_str("        i = next;\n");
    out.push_str("        apply_parsed_op(host, op, styles, texts)?;\n");
    out.push_str("    }\n");
    out.push_str("    Ok(())\n");
    out.push_str("}\n\n");

    out.push_str("pub(crate) fn apply_parsed_op<H: ApplyMutationsHost>(\n");
    out.push_str("    host: &mut H,\n");
    out.push_str("    op: Op,\n");
    out.push_str("    styles: &[f32],\n");
    out.push_str("    texts: &js_sys::Array,\n");
    out.push_str(") -> Result<(), JsValue> {\n");
    out.push_str("    match op {\n");

    for op in &proto.opcodes {
        let variant = to_pascal(&op.name);
        if op.params.is_empty() {
            continue;
        }
        let fields: Vec<String> = op.params.iter().map(|p| p.name.clone()).collect();
        out.push_str(&format!(
            "        Op::{variant} {{ {} }} => {{\n",
            fields.join(", ")
        ));
        out.push_str(&dispatch_op_body(&op.name, &op.params));
        out.push_str("        }\n");
    }

    out.push_str("    }\n");
    out.push_str("}\n");
    out
}

fn dispatch_op_body(op_name: &str, _params: &[Param]) -> String {
    match op_name {
        "APPEND_CHILD" => {
            "            host.tree_mut().element_append_child(\n                ElementId::from_u64(parent_id),\n                ElementId::from_u64(child_id),\n            );\n            Ok(())\n".to_string()
        }
        "INSERT_BEFORE" => {
            "            host.tree_mut().element_insert_before(\n                ElementId::from_u64(parent_id),\n                ElementId::from_u64(child_id),\n                ElementId::from_u64(before_id),\n            );\n            Ok(())\n".to_string()
        }
        "REMOVE" => {
            "            host.remove_subtree(ElementId::from_u64(id));\n            Ok(())\n".to_string()
        }
        "SET_ROOT" => {
            "            host.tree_mut().set_root(ElementId::from_u64(id));\n            Ok(())\n".to_string()
        }
        "SET_STYLE" => {
            r#"            let slice = styles
                .get(style_offset..style_offset + style_len)
                .ok_or_else(|| JsValue::from_str("styles slice out of bounds in OP_SET_STYLE"))?;
            let props = decode_style_packet(slice)?;
            host.tree_mut().element_set_style(ElementId::from_u64(id), &props);
            Ok(())
"#.to_string()
        }
        "SET_TRANSFORM" => {
            r#"            let matrix = if has_matrix {
                Some(matrix)
            } else {
                None
            };
            host.tree_mut().element_set_transform(ElementId::from_u64(id), matrix);
            Ok(())
"#.to_string()
        }
        "SET_SCROLL_OFFSET" => {
            r#"            host.tree_mut().element_set_scroll_offset(
                ElementId::from_u64(id),
                x as f32,
                y as f32,
            );
            Ok(())
"#.to_string()
        }
        "FOCUS" => {
            r#"            host.apply_focus(ElementId::from_u64(id));
            Ok(())
"#.to_string()
        }
        "BLUR" => {
            r#"            host.apply_blur(ElementId::from_u64(id));
            Ok(())
"#.to_string()
        }
        "CREATE" => {
            r#"            let k = ElementKind::from_u32(kind)
                .ok_or_else(|| JsValue::from_str(&format!("unknown element kind {kind}")))?;
            host.tree_mut().element_create(id, k);
            Ok(())
"#.to_string()
        }
        "SET_TEXT" => {
            r#"            if text_index >= texts.length() as usize {
                return Err(JsValue::from_str("text index out of bounds in OP_SET_TEXT"));
            }
            let text = texts
                .get(text_index as u32)
                .as_string()
                .ok_or_else(|| JsValue::from_str("text table entry is not a string in OP_SET_TEXT"))?;
            host.tree_mut()
                .element_set_text(ElementId::from_u64(id), &text);
            Ok(())
"#.to_string()
        }
        "UNSET_STYLE" => {
            r#"            let kind = unset_kind_from_u32(kind)?;
            host.tree_mut()
                .element_unset_style(ElementId::from_u64(id), &[kind]);
            Ok(())
"#.to_string()
        }
        other => format!(
            "            Err(JsValue::from_str(\"unknown op {other}\"))\n",
        ),
    }
}

/// Flatten style tag params: expand compound types (color, dimension) into raw f32 fields.
fn flatten_tag_params(params: &[Param], proto: &Proto) -> Vec<(String, String)> {
    let mut result = Vec::new();
    for p in params {
        // Check if this param type matches a known compound type
        if let Some(td) = proto.types.iter().find(|t| t.name == p.typ) {
            // Expand fields
            for f in &td.fields {
                let fname = format!("{}_{}", p.name, f.name);
                result.push((fname, "f32".to_string()));
            }
        } else if p.typ == "string" {
            result.push((p.name.clone(), "String".to_string()));
        } else {
            // f32, display enums, etc. — all stored as f32
            result.push((p.name.clone(), "f32".to_string()));
        }
    }
    result
}

fn event_match_pattern(ev: &Entry, qualified: bool) -> String {
    let variant = to_pascal(&ev.name);
    let prefix = if qualified { "hayate_core::Event::" } else { "Event::" };
    if ev.params.is_empty() {
        format!("{}{}", prefix, variant)
    } else {
        let fields: Vec<String> = ev.params.iter().map(|p| p.name.clone()).collect();
        format!("{}{} {{ {} }}", prefix, variant, fields.join(", "))
    }
}

fn event_match_wildcard(ev: &Entry) -> String {
    let variant = to_pascal(&ev.name);
    if ev.params.is_empty() {
        format!("Event::{}", variant)
    } else {
        format!("Event::{} {{ .. }}", variant)
    }
}

fn encode_event_wire_param_push(param: &Param, field: &str) -> String {
    match param.typ.as_str() {
        "element_id" => format!(
            "            out.push(EventWireValue::Number({}.to_u64() as f64));\n",
            field
        ),
        "string" => format!(
            "            out.push(EventWireValue::Text({}.clone()));\n",
            field
        ),
        "f32" | "f64" | "u32" | "usize" | "bool" => {
            format!("            out.push(EventWireValue::Number(*{} as f64));\n", field)
        }
        other => panic!("unsupported event param type: {other}"),
    }
}

fn generate_encode_event(proto: &Proto) -> String {
    let mut out = String::new();

    out.push_str("#[derive(Debug, Clone, PartialEq)]\n");
    out.push_str("pub enum EventWireValue {\n");
    out.push_str("    Number(f64),\n");
    out.push_str("    Text(String),\n");
    out.push_str("}\n\n");

    out.push_str("pub fn encode_event_wire(ev: &hayate_core::Event) -> Vec<EventWireValue> {\n");
    out.push_str("    match ev {\n");

    for ev in &proto.event_kinds {
        out.push_str(&format!("        {} => {{\n", event_match_pattern(ev, true)));
        out.push_str("            let mut out = Vec::new();\n");
        out.push_str(&format!(
            "            out.push(EventWireValue::Number({}.0));\n",
            ev.value
        ));
        for p in &ev.params {
            out.push_str(&encode_event_wire_param_push(p, &p.name));
        }
        out.push_str("            out\n");
        out.push_str("        }\n");
    }

    out.push_str("    }\n");
    out.push_str("}\n\n");

    out.push_str("pub fn encode_event(ev: &hayate_core::Event) -> js_sys::Array {\n");
    out.push_str("    use wasm_bindgen::JsValue;\n");
    out.push_str("    let sub = js_sys::Array::new();\n");
    out.push_str("    for atom in encode_event_wire(ev) {\n");
    out.push_str("        match atom {\n");
    out.push_str("            EventWireValue::Number(n) => { sub.push(&JsValue::from_f64(n)); }\n");
    out.push_str("            EventWireValue::Text(s) => { sub.push(&JsValue::from_str(&s)); }\n");
    out.push_str("        }\n");
    out.push_str("    }\n");
    out.push_str("    sub\n");
    out.push_str("}\n\n");

    out.push_str("pub fn encode_events(events: &[hayate_core::Event]) -> js_sys::Array {\n");
    out.push_str("    let result = js_sys::Array::new();\n");
    out.push_str("    for ev in events {\n");
    out.push_str("        result.push(&encode_event(ev));\n");
    out.push_str("    }\n");
    out.push_str("    result\n");
    out.push_str("}\n\n");

    out.push_str(
        "pub fn encode_deliveries(deliveries: &[hayate_core::EventDelivery]) -> js_sys::Array {\n",
    );
    out.push_str("    let result = js_sys::Array::new();\n");
    out.push_str("    for delivery in deliveries {\n");
    out.push_str("        let sub = encode_event(&delivery.event);\n");
    out.push_str("        let row = js_sys::Array::new();\n");
    out.push_str("        row.push(&JsValue::from_f64(delivery.listener_id.to_u64() as f64));\n");
    out.push_str("        for i in 0..sub.length() {\n");
    out.push_str("            row.push(&sub.get(i));\n");
    out.push_str("        }\n");
    out.push_str("        result.push(&row);\n");
    out.push_str("    }\n");
    out.push_str("    result\n");
    out.push_str("}\n");

    out
}

fn event_field_rust_type(typ: &str) -> String {
    match typ {
        "element_id" => "ElementId".to_string(),
        "string" => "String".to_string(),
        "f32" => "f32".to_string(),
        "f64" => "f64".to_string(),
        "u32" => "u32".to_string(),
        "usize" => "usize".to_string(),
        "bool" => "bool".to_string(),
        other => panic!("unsupported event param type: {other}"),
    }
}

fn generate_event_types(proto: &Proto) -> String {
    let mut out = String::new();
    out.push_str(GENERATED_HEADER);
    out.push_str("use super::id::ElementId;\n\n");

    out.push_str("/// Semantic interaction events (ADR-0031).\n");
    out.push_str("#[derive(Clone, Debug)]\n");
    out.push_str("pub enum Event {\n");
    for ev in &proto.event_kinds {
        if let Some(desc) = &ev.description {
            for line in desc.lines() {
                out.push_str(&format!("    /// {}\n", line));
            }
        }
        let variant = to_pascal(&ev.name);
        if ev.params.is_empty() {
            out.push_str(&format!("    {},\n", variant));
        } else {
            out.push_str(&format!("    {} {{\n", variant));
            for p in &ev.params {
                out.push_str(&format!(
                    "        {}: {},\n",
                    p.name,
                    event_field_rust_type(&p.typ)
                ));
            }
            out.push_str("    },\n");
        }
    }
    out.push_str("}\n\n");

    let doc_events: Vec<_> = proto
        .event_kinds
        .iter()
        .filter(|ev| ev.document_runtime)
        .collect();

    out.push_str("/// Event kinds registerable via `register_listener`.\n");
    out.push_str("#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash)]\n");
    out.push_str("pub enum DocumentEventKind {\n");
    for ev in &doc_events {
        out.push_str(&format!("    {},\n", to_pascal(&ev.name)));
    }
    out.push_str("}\n\n");

    out.push_str("impl DocumentEventKind {\n");
    out.push_str("    pub fn bubbles(self) -> bool {\n");
    out.push_str("        match self {\n");
    for ev in &doc_events {
        let arm = if ev.bubbles { "true" } else { "false" };
        out.push_str(&format!(
            "            Self::{} => {},\n",
            to_pascal(&ev.name),
            arm
        ));
    }
    out.push_str("        }\n");
    out.push_str("    }\n\n");

    out.push_str("    pub fn from_u32(value: u32) -> Option<Self> {\n");
    out.push_str("        match value {\n");
    for ev in &doc_events {
        out.push_str(&format!(
            "            {} => Some(Self::{}),\n",
            ev.value,
            to_pascal(&ev.name)
        ));
    }
    out.push_str("            _ => None,\n");
    out.push_str("        }\n");
    out.push_str("    }\n");
    out.push_str("}\n\n");

    out.push_str("/// Map a runtime `Event` to its document kind, if registerable.\n");
    out.push_str("pub fn event_document_kind(event: &Event) -> Option<DocumentEventKind> {\n");
    out.push_str("    match event {\n");
    for ev in &doc_events {
        out.push_str(&format!(
            "        {} => Some(DocumentEventKind::{}),\n",
            event_match_wildcard(ev),
            to_pascal(&ev.name)
        ));
    }
    out.push_str("        _ => None,\n");
    out.push_str("    }\n");
    out.push_str("}\n");

    out
}

/// Convert SCREAMING_SNAKE_CASE to PascalCase.
fn to_pascal(s: &str) -> String {
    s.split('_')
        .map(|word| {
            let mut c = word.chars();
            match c.next() {
                None => String::new(),
                Some(f) => f.to_uppercase().collect::<String>() + &c.as_str().to_lowercase(),
            }
        })
        .collect()
}
