// @generated by @torimi/wire-contract/scripts/generate.mjs. DO NOT EDIT.

export const BUNDLE_ROUTE = "/bundle.js" as const;
export const DEMO_MANIFEST_ROUTE = "/demos.json" as const;
export const LOG_ROUTE_PREFIX = "/log/" as const;
export const RELOAD_ROUTE = "/reload" as const;
export const RELOAD_MESSAGE = "reload" as const;
export const HAYATE_HOST_GLOBAL = "__hayateHost" as const;
export const HAYATE_LOG_GLOBAL = "__hayateLog" as const;
export const TORIMI_MOUNT_GLOBAL = "__torimiMount" as const;
export const TORIMI_PROTOCOL_VERSION_GLOBAL = "__torimiProtocolVersion" as const;
export const TSUBAME_GLOBAL = "__tsubame" as const;

export const LOG_LEVEL_DEBUG = "debug" as const;
export const LOG_LEVEL_ERROR = "error" as const;
export const LOG_LEVEL_INFO = "info" as const;
export const LOG_LEVEL_LOG = "log" as const;
export const LOG_LEVEL_WARN = "warn" as const;
export const KNOWN_LOG_LEVELS = [LOG_LEVEL_DEBUG, LOG_LEVEL_ERROR, LOG_LEVEL_INFO, LOG_LEVEL_LOG, LOG_LEVEL_WARN] as const;
export type LogLevel = string;
export function isKnownLogLevel(value: string): value is (typeof KNOWN_LOG_LEVELS)[number] {
  return (KNOWN_LOG_LEVELS as readonly string[]).includes(value);
}
export const LOG_SOURCE_HOST = "host" as const;
export const LOG_SOURCE_JS = "js" as const;
export const KNOWN_LOG_SOURCES = [LOG_SOURCE_HOST, LOG_SOURCE_JS] as const;
export type LogSource = string;
export function isKnownLogSource(value: string): value is (typeof KNOWN_LOG_SOURCES)[number] {
  return (KNOWN_LOG_SOURCES as readonly string[]).includes(value);
}
export const RELOAD_MESSAGE_RELOAD = "reload" as const;
export const KNOWN_RELOAD_MESSAGES = [RELOAD_MESSAGE_RELOAD] as const;
export type ReloadMessage = string;
export function isKnownReloadMessage(value: string): value is (typeof KNOWN_RELOAD_MESSAGES)[number] {
  return (KNOWN_RELOAD_MESSAGES as readonly string[]).includes(value);
}

export interface DemoManifest {
  readonly demos: readonly DemoManifestEntry[];
}

export interface DemoManifestEntry {
  readonly bundleUrl: string;
  readonly name: string;
}

export interface LogBatch {
  readonly deviceLabel: string;
  readonly entries: readonly LogEntry[];
}

export interface LogEntry {
  readonly level: string;
  readonly message: string;
  readonly seq: number;
  readonly source: string;
  readonly ts: number;
}

export interface WireIssue {
  readonly path: string;
  readonly expected: string;
  readonly actualType: string;
}

export type WireValidationResult<T> =
  | { readonly ok: true; readonly value: T }
  | { readonly ok: false; readonly issues: readonly WireIssue[] };

type JsonSchema = Readonly<Record<string, unknown>>;
const WIRE_SCHEMA = {
  "$defs": {
    "DemoManifest": {
      "additionalProperties": true,
      "properties": {
        "demos": {
          "items": {
            "$ref": "#/$defs/DemoManifestEntry"
          },
          "type": "array"
        }
      },
      "required": [
        "demos"
      ],
      "type": "object"
    },
    "DemoManifestEntry": {
      "additionalProperties": true,
      "properties": {
        "bundleUrl": {
          "type": "string"
        },
        "name": {
          "type": "string"
        }
      },
      "required": [
        "name",
        "bundleUrl"
      ],
      "type": "object"
    },
    "LogBatch": {
      "additionalProperties": true,
      "properties": {
        "deviceLabel": {
          "type": "string"
        },
        "entries": {
          "items": {
            "$ref": "#/$defs/LogEntry"
          },
          "type": "array"
        }
      },
      "required": [
        "deviceLabel",
        "entries"
      ],
      "type": "object"
    },
    "LogEntry": {
      "additionalProperties": true,
      "properties": {
        "level": {
          "minLength": 1,
          "type": "string"
        },
        "message": {
          "type": "string"
        },
        "seq": {
          "minimum": 0,
          "type": "integer"
        },
        "source": {
          "minLength": 1,
          "type": "string"
        },
        "ts": {
          "type": "number"
        }
      },
      "required": [
        "seq",
        "ts",
        "source",
        "level",
        "message"
      ],
      "type": "object"
    }
  }
} as const;

function actualType(value: unknown): string {
  if (value === null) return 'null';
  if (Array.isArray(value)) return 'array';
  return typeof value;
}

function check(value: unknown, rawSchema: JsonSchema, path: string, issues: WireIssue[]): void {
  let candidate = rawSchema;
  if (typeof candidate.$ref === 'string') {
    const name = candidate.$ref.split('/').at(-1);
    candidate = (WIRE_SCHEMA.$defs as Record<string, JsonSchema>)[name ?? ''] ?? {};
  }
  const expected = typeof candidate.type === 'string' ? candidate.type : 'valid wire value';
  const fail = (): void => { issues.push({ path, expected, actualType: actualType(value) }); };
  if (candidate.type === 'object') {
    if (value === null || typeof value !== 'object' || Array.isArray(value)) return fail();
    const record = value as Record<string, unknown>;
    for (const field of (candidate.required as readonly string[] | undefined) ?? []) {
      if (!Object.prototype.hasOwnProperty.call(record, field)) {
        issues.push({ path: path + '.' + field, expected: 'required', actualType: 'missing' });
      }
    }
    for (const [field, fieldSchema] of Object.entries((candidate.properties as Record<string, JsonSchema> | undefined) ?? {})) {
      if (Object.prototype.hasOwnProperty.call(record, field)) check(record[field], fieldSchema, path + '.' + field, issues);
    }
    return;
  }
  if (candidate.type === 'array') {
    if (!Array.isArray(value)) return fail();
    value.forEach((item, index) => check(item, candidate.items as JsonSchema, path + '[' + index + ']', issues));
    return;
  }
  if (candidate.type === 'integer') {
    if (typeof value !== 'number' || !Number.isFinite(value) || !Number.isInteger(value) || (typeof candidate.minimum === 'number' && value < candidate.minimum)) fail();
    return;
  }
  if (candidate.type === 'number') {
    if (typeof value !== 'number' || !Number.isFinite(value)) fail();
    return;
  }
  if (candidate.type === 'string') {
    if (typeof value !== 'string' || (typeof candidate.minLength === 'number' && value.length < candidate.minLength)) fail();
    return;
  }
  if (candidate.type === 'boolean' && typeof value !== 'boolean') fail();
}

function validate<T>(name: keyof typeof WIRE_SCHEMA.$defs, value: unknown): WireValidationResult<T> {
  const issues: WireIssue[] = [];
  check(value, WIRE_SCHEMA.$defs[name], '$', issues);
  return issues.length === 0 ? { ok: true, value: value as T } : { ok: false, issues };
}

export function validateDemoManifest(value: unknown): WireValidationResult<DemoManifest> {
  return validate('DemoManifest', value);
}
export function validateDemoManifestEntry(value: unknown): WireValidationResult<DemoManifestEntry> {
  return validate('DemoManifestEntry', value);
}
export function validateLogBatch(value: unknown): WireValidationResult<LogBatch> {
  return validate('LogBatch', value);
}
export function validateLogEntry(value: unknown): WireValidationResult<LogEntry> {
  return validate('LogEntry', value);
}

export const devServerContract = {
  bundleRoute: BUNDLE_ROUTE,
  reloadRoute: RELOAD_ROUTE,
  reloadMessage: RELOAD_MESSAGE,
  logRoutePrefix: LOG_ROUTE_PREFIX,
} as const;

export const demoEndpointContract = { demoManifestRoute: DEMO_MANIFEST_ROUTE } as const;
