use std::env;
use std::fs;
use std::io::Write;
use std::path::PathBuf;

fn main() {
    let manifest_dir = env::var("CARGO_MANIFEST_DIR").unwrap();
    let manifest_path = PathBuf::from(&manifest_dir);
    let spec_dir = manifest_path.join("../../../proto/spec");
    let generated_dir = manifest_path.join("../../../proto/generated");

    for section in [
        "types",
        "enums",
        "opcodes",
        "style_tags",
        "event_kinds",
        "element_kinds",
        "unset_kinds",
        "modifier_keys",
    ] {
        let path = spec_dir.join(format!("{section}.json"));
        println!("cargo:rerun-if-changed={}", path.display());
    }
    println!(
        "cargo:rerun-if-changed={}",
        spec_dir.join("manifest.json").display()
    );
    for file in ["protocol.rs", "dispatch.rs", "dom_style_mapper.rs"] {
        println!(
            "cargo:rerun-if-changed={}",
            generated_dir.join(file).display()
        );
    }

    let fonts_json = manifest_path.join("fonts.json");
    println!("cargo:rerun-if-changed={}", fonts_json.display());
    generate_builtin_fonts(&fonts_json);
}

#[derive(serde::Deserialize)]
struct FontEntry {
    family: String,
    url: String,
}

fn generate_builtin_fonts(fonts_json: &PathBuf) {
    let text = fs::read_to_string(fonts_json).expect("read fonts.json");
    let entries: Vec<FontEntry> = serde_json::from_str(&text).expect("parse fonts.json");

    let out_dir = PathBuf::from(env::var("OUT_DIR").unwrap());
    let out_path = out_dir.join("builtin_fonts_gen.rs");
    let mut file = fs::File::create(&out_path).expect("create builtin_fonts_gen.rs");

    writeln!(
        file,
        "// @generated by build.rs from fonts.json — do not edit."
    )
    .unwrap();
    writeln!(file).unwrap();
    writeln!(
        file,
        "/// Built-in family-name → CDN URL table (ADR-0043, ADR-0061)."
    )
    .unwrap();
    writeln!(
        file,
        "/// fontique/skrifa does NOT support WOFF2 — TTF/OTF only."
    )
    .unwrap();
    writeln!(
        file,
        "pub fn builtin_font_url(family: &str) -> Option<&'static str> {{"
    )
    .unwrap();
    writeln!(file, "    match family {{").unwrap();

    for entry in &entries {
        writeln!(
            file,
            "        {:?} => Some({:?}),",
            entry.family, entry.url
        )
        .unwrap();
    }

    writeln!(file, "        _ => None,").unwrap();
    writeln!(file, "    }}").unwrap();
    writeln!(file, "}}").unwrap();
}
